window.skcsacompatVersion="3";window.skcsapacketVersion="1";window.skcsauseCorsForInitialRequest="1";window.skcsauseJsonFormatForInitialCorsRequest="1";window.CelebrusDataPrivacy={MAY_CONTAIN_PERSONAL_DATA:1,ANONYMOUS_DATA_ONLY:2};
window.skcsapPO=function(a,k){window.localStorage&&window.localStorage.setItem("skcsaP3P",a);var f=new Date;f.setFullYear(f.getFullYear()+20);window.skcsaSC("skcsaP3P="+a,f.toGMTString());k&&window.skcsaSC("skcsaP3P="+a,f.toGMTString(),"","","","",k,!1);"optedOut"==a&&window.skcsastopEvents&&window.skcsastopEvents();window.skcsadoReInit?window.skcsadoReInit():window.skcsaGo&&!window.skcsawid&&skcsaGo()};
window.skcsaoptOut=function(a){window.skcsapPO("optedOut",a)};window.skcsaoptIn=function(a){window.skcsapPO("optedIn",a)};window.skcsaanonymous=function(a){window.skcsapPO("anonymous",a)};
function skcsasessionShutdownPeriodExceeded(){var a=!1,a=document.cookie?-1<document.cookie.indexOf("skcsaSF="):null!=window.sessionStorage.getItem("skcsaSF");if(!a)return!1;a=window.skcsafindCookieVal("skcsaSF");a=parseInt(a,10);return-1==a||isNaN(a)?!1:Math.abs((new Date).valueOf()-a)>10800000?!0:!1}
function skcsaperiodicAssessShutdownState(){window.skcsafindCookieVal("skcsaSF")&&(window.skcsasessionShutdownPeriodExceeded()?(window.skcsadoDeleteCookie&&window.skcsadoDeleteCookie("skcsaSF"),window.skcsalstActv=(new Date).valueOf(),window.skcsaqNI=!0,window.skcsafindCookieVal("skcsaP3P",1),window.skcsaresetCSA&&window.skcsaresetCSA(),window.skcsaexecuteReInitNow&&window.skcsaexecuteReInitNow()):window.setTimeout(skcsaperiodicAssessShutdownState,
1E4))}var skcsaGL=-1==document.cookie.indexOf("skcsaSF=")&&-1==document.cookie.indexOf("skcsaStopFlag=y")&&-2!=window.skcsasn;window.skcsapendingManualEvents||(window.skcsapendingManualEvents=[]);window.skcsaqueuedYoutubeReferences||(window.skcsaqueuedYoutubeReferences=[]);
window.skcsasn||(window.skcsaevent=function(a){window.skcsapendingManualEvents.push({eventTypeIdentifier:"basket",payload:a})},window.skcsaclick=function(a){a&&window.skcsapendingManualEvents.push({eventTypeIdentifier:"click",payload:a})},window.skcsatextchange=function(a){a&&window.skcsapendingManualEvents.push({eventTypeIdentifier:"textchange",payload:a})},window.skcsaformsubmit=function(a){window.skcsapendingManualEvents.push({eventTypeIdentifier:"formsubmit",
payload:a})},window.skcsaSendJsonData=function(a,k){window.skcsapendingManualEvents.push({eventTypeIdentifier:"jsondata",payload:a,dataPrivacyVal:k})},window.skcsatrackYouTubeIframePlayer=function(a,k){window.skcsaqueuedYoutubeReferences.push({playerRef:a,playerIdentifier:k})});window.skcsainitialExecutionCanProceed=function(){return 1==skcsaGL?window.skcsawindowID?!1:!0:!1};
window.skcsablockExecutionForInsertAlreadyPresent=function(){return window.skcsagetSD?!0:!1};
window.skcsaSL=function(){function a(){l.skcsawindowID="_"+(new Date).getTime()+"0."+window.skcsagenerateUUID()+"_";var m=window.skcsafindCookieVal("skcsasession"),d=window.skcsafindCookieVal("skcsapersisted"),a=window.skcsafindCookieVal("usy46gabsosd"),b,f,c,e,k,n=!1,p=!1;a&&(n=!0);m&&(p=!0);var g=m?m.split("_"):null;if(g&&5==g.length)b="x"+g[0]+"_"+g[3],f=g[1],c=g[2],e=g[3],k=g[4],A=e,B=b;else{for(b=""+Math.floor(9999*Math.random()+1);4>b.length;)b="0"+b;a&&
(b=A,e=window.skcsafindCookieVal("usy46gabsosd"))&&(g=e.lastIndexOf("_"),-1!=g&&(e=e.substring(g+1),b=4==e.length&&e.match(Q)?e:b));A=b;B=l.skcsawindowID+A;try{l.top.name||(l.top.name=l.skcsawindowID)}catch(r){}b=B;e=A}return{sessionInfo:b,lastActivityTS:f,sessionStartTS:c,loadBalancerID:e,sessionKey:k,sessionCookieVal:m,persistedCookieVal:d,legacyCookieVal:a,foundLegacyCookie:n,foundSessionCookie:p}}function k(){var m=window.skcsafindCookieVal("skcsapersisted");if(m){var d=
m.split("_");return 7!=d.length?null:{dbID:d[0],rtID:d[1],udID:d[2],acqTS:d[3],recSN:d[4],recTS:d[5],frq:d[6],cookieVal:m}}return null}function f(){if(F){var m="_";F.dbID&&(m=F.dbID+m);F.rtID&&(m+=F.rtID);return m}return window.skcsafindCookieVal("skcsaDBID",1)}function e(){return u&&u.sessionKey?u.sessionKey:window.skcsafindCookieVal("skcsakey")}function c(m){return I?(m=I(m),m=m.replace(/'/g,"%27"),m=m.replace(/~/g,"%7E")):escape(m)}function p(m){return"https:"==(""+location.protocol).toLowerCase()||
1==l.skcsaForceSecure?"skcsassl"+m:"skcsatcp"+m}function g(m){m=p(m);try{if(l.sessionStorage){var d=l.sessionStorage.getItem(m);if(d)return""+d}}catch(a){}return""}function r(m,d){var a=p(m);try{l.sessionStorage&&l.sessionStorage.setItem(a,d)}catch(b){}}function n(m){try{var d=g(m),a=parseInt(d);return isNaN(a)?0:a}catch(b){return 0}}function y(){return n("lastQueuePointer")}function z(m){try{var d=parseInt(g(m));isNaN(d)&&(d=0);49==d?d=0:d++;r(m,""+d)}catch(a){}}function w(){var m=
n("lastProcessPointer"),d=y();m<d&&z("lastProcessPointer")}function v(){var m=y();g(m)&&z("lastQueuePointer")}function t(){var m=n("lastProcessPointer"),d="";try{d=g(m)}catch(a){}try{var f=p(m);try{l.sessionStorage&&l.sessionStorage.removeItem(f)}catch(a){}}catch(a){}return d}function x(m){m=m.replace(/&/g,"+");m=m.replace(/%/g,"q");m=m.replace(/(..)(..)/g,"$2$1");m=m.replace(/(........)(.....)/g,"$2$1");var d=f(),a=e();a&&(d+="_"+a);return m="z="+c(d)+"&y="+m}function J(a,d){return a?-1!==a.indexOf(d,
a.length-d.length):!1}function K(a){function d(){w();b()}function f(){w();b()}function b(){var b=t();if(b)if(0==b.indexOf("reinit:"))d();else{window.CelebrusLoggingUtils&&window.CelebrusLoggingUtils.logEventQueued(b);var c;var e=R;try{var g="https://cxa.skfh.com.tw";J(b,":http")&&(g="http://cxa.skfh.com.tw");var g=g+"/"+A+"/",b=x(b),k="ZDY21YGC90LI/uw2jde932.bmp?";e&&(k="1"==skcsauseJsonFormatForInitialCorsRequest?"AEZ32ZHD01MJ/jsEvent.json?":"AEZ32ZHD01MJ/jsEvent.js?");c=g+k+b}catch(n){c=null}if(c)if(R)S(c,d,f);else{null==
l.skcsasImgArr[0]&&(l.skcsasImgArr[0]=new Image,b=l.skcsasImgArr[0],b.attachEvent?b.attachEvent("onload",d):b.addEventListener&&b.addEventListener("load",d,!1),b=l.skcsasImgArr[0],e=f,b.attachEvent?b.attachEvent("onerror",e):b.addEventListener&&b.addEventListener("error",e,!1));try{l.skcsasImgArr[0].src=c}catch(n){f()}}else f()}else a()}l.skcsasImgArr=[];b()}function G(a,d,f,b){return(d=window.skcsafindCookieVal(a))?a+"="+d:""}function L(a,d){""!=d&&(""!=a&&(a+=
"; "),a+=d);return a}function S(a,d,f){var b=a.indexOf("?"),c="",e="";-1==b?c=a:(c=a.substring(0,b),e=a.substring(b+1));var g=new XMLHttpRequest;g.open("POST",c,!0);g.withCredentials=!0;g.setRequestHeader("Content-Type","text/plain;charset=UTF-8");d&&(g.onload=function(){d(g)});f&&(g.onerror=function(){f(g)});try{g.send(e)}catch(k){}}if(!window.skcsablockExecutionForInsertAlreadyPresent()){var l=window,D=document,U=location,T=D.cookie,A="",B="",Q=/^[a-z0-9]+$/i;l.skcsaLF=!0;l.skcsaTCP=
"http://cxa.skfh.com.tw";l.skcsaSSL="https://cxa.skfh.com.tw";l.skcsagPr=function(a){var d=(""+U.protocol).toLowerCase();if("https:"==d)return"https://cxa.skfh.com.tw";a||(a=d);1==l.skcsaForceSecure&&(a="https:");return"http:"==a||"http"==a?"http://cxa.skfh.com.tw":"https://cxa.skfh.com.tw"};window.skcsaclearStoppedState=function(){window.skcsadoDeleteCookie&&window.skcsadoDeleteCookie("skcsaSF")};window.skcsastop=function(){window.skcsadeleteSessionCookie&&window.skcsadeleteSessionCookie();if(document.cookie)window.skcsaSC&&
window.skcsadoDeleteCookie("skcsakey");else try{window.sessionStorage&&window.sessionStorage.removeItem("skcsakey")}catch(a){}window.skcsaoTP=!1;window.skcsaSC&&window.skcsaSC("skcsaSF="+(new Date).valueOf())};var I=l.encodeURIComponent,u="",F="";window.skcsacookieList=[];l.skcsagC=function(a){var d="usy46gabsosd skcsauvt skcsaDBID skcsakey skcsasession skcsapersisted skcsaP3P".split(" "),f="";if(true){for(var b=
document.cookie,c=0;c<d.length;c++){var e=G(d[c],a);e&&(f=L(f,e),b=-1<b.indexOf(e+"; ")?b.replace(e+"; ",""):-1<b.indexOf(e+";")?b.replace(e+";",""):b.replace(e,""))}return{celebrusCookies:f,siteCookies:b}}d="usy46gabsosd skcsauvt skcsaDBID skcsakey skcsasession skcsapersisted skcsaP3P".split(" ");for(c=0;c<d.length;c++)(e=G(d[c],a))&&(f=L(f,e));d="";if(0<window.skcsacookieList.length)for(b=0,c=window.skcsacookieList.length;b<c;b++)(e=G(window.skcsacookieList[b],
a))&&(d=L(d,e));return{celebrusCookies:f,siteCookies:d}};l.skcsaae=function(){l.skcsawid||((new Date).valueOf()-l.skcsaTm>30000?0===l.frames.length&&window.skcsadoDeleteCookie&&(window.skcsadoDeleteCookie("usy46gabsosd"),window.skcsadoDeleteCookie("skcsasession"),l.skcsaSC("skcsaSF="+(new Date).valueOf()),skcsaperiodicAssessShutdownState()):l.setTimeout(l.skcsaae,2E3))};l.skcsaclient_event=function(a,d){if(!(-1<document.cookie.indexOf("skcsaSF="))){var c=
window;c.skcsaqueueUserEvent?c.skcsaqueueUserEvent(a,d):c.setTimeout("skcsaclient_event('"+a+"','"+d+"');",500)}};l.skcsaGP=function(a){return null};l.skcsaGPWID=function(a){return a.skcsawindowID};l.skcsaexecuteJsonResponse=function(a,d){var c=a,b=window.skcsawid;d||(c=JSON.parse(a));var f=c.windowVariables,e;for(e in f)0===e.indexOf("skcsa")&&(window[e]="skcsauSC"==e||"skcsauseCors"==e||"skcsadoCapture"==e||"skcsalookups"==e||"skcsauseJsonFormatRequest"==
e?"true"==f[e]:"skcsaidl"==e||"skcsasST"==e||"skcsamST"==e?parseInt(f[e],10):f[e]);if(f=c.queueNavigatorInfo)window.skcsaqNI=f;if(c.isExcludedFromSample&&skcsasetShutdown)skcsasetShutdown();else{(f=c.isMinimalCookieFormat)?(window.skcsadeleteLegacyCookies&&window.skcsadeleteLegacyCookies(),skcsasessionset(c.sessionCookieValue)):(skcsalegacyset(c.sn,c.lastActivityTs,c.sessionStartTs,c.lbId),skcsakeyset(c.sessionKey));window.skcsadoCelebrusInsertInvocation&&
window.skcsadoCelebrusInsertInvocation(b);if(b=c.persistedCookieValues)f?skcsapersisted(b.dbID,b.rtId,b.acq,b.sn,b.cookieName,b.cookieExpiry,b.frq,b.acqTS,b.recTS,b.trackDevices):(b.trackDevices?skcsauvt(b.acq,b.sn,b.cookieExpiry,b.acqTS,b.recTS):skcsadoDeleteCookie&&skcsadoDeleteCookie("skcsauvt"),skcsadoDeleteCookie&&skcsadoDeleteCookie("skcsaDBID"),skcsaDBIDset(b.dbID+"_"+b.rtId,b.cookieExpiry));if(c.contentResponse&&window.skcsaRTEHandler){b=
[];try{b=JSON.parse(c.contentResponse)}catch(g){}try{window.skcsaRTEHandler.handleResponse(b)}catch(g){}}}};l.skcsadynamicCreateScript=function(a,d,c){var b=document;if(b.getElementById){var e=b.getElementsByTagName("head").item(0);e&&(b=b.createElement("SCRIPT"),b.type="text/javascript",b.id=a,d&&(b.src=d),c&&(b.text=c),e.appendChild(b))}};l.skcsaLC=function(a,d){"skcsacsaId"!=d&&window.skcsaisCorsPermitted()?S(a,function(a){200===a.status&&(a=a.responseText,window.skcsaisCorsPermitted()&&
"1"==window.skcsauseJsonFormatForInitialCorsRequest?a&&window.skcsaexecuteJsonResponse(a):window.skcsadynamicCreateScript(d,"",a))},null):window.skcsadynamicCreateScript(d,a,"")};window.skcsaisCorsPermitted=function(){if("function"==typeof XMLHttpRequest||"object"==typeof XMLHttpRequest){var a=new XMLHttpRequest;return"1"==window.skcsauseCorsForInitialRequest&&"withCredentials"in a}return!1};var R=window.sessionStorage&&window.skcsaisCorsPermitted();l.skcsaGP=
function(a){try{return a===a.parent?null:a.parent}catch(d){}return null};l.skcsaTWID="AUTOSET";window.skcsaresetCSA=function(){window.skcsadoResetCSA&&window.skcsadoResetCSA()};window.skcsadoReInit=function(a){try{var d=window.sessionStorage?!0:!1;d&&window.skcsasessionStorageEnabled&&(d=window.skcsasessionStorageEnabled());if(d&&window.skcsaoTP){v();var c=y(),d="",d=g(c);d||(r(c,"reinit:"+window.skcsawindowID+(a?":1":":0")),v())}else window.skcsaexecuteReInitNow&&
window.skcsaexecuteReInitNow()}catch(b){}};window.skcsaexecuteReInitNow=function(a){window.skcsaqBU&&window.skcsaqBU();window.skcsaclearStoppedState&&window.skcsaclearStoppedState();l.skcsalstActv=(new Date).valueOf();window.skcsafindCookieVal("skcsaP3P",1);window.skcsaresetCSA&&window.skcsaresetCSA();a&&(window.skcsadeleteSessionCookie&&window.skcsadeleteSessionCookie(),v());if(window.skcsaAppBridgeV2){window.skcsaawaitingAppResponse=
!0;try{var d=window.skcsafindCookieVal("skcsapersisted");window.skcsaAppBridgeV2.requestSessionInformation(location.href,d,window.skcsawindowId,!0)}catch(c){window.skcsaappSessionObject="",window.skcsaawaitingAppResponse=!1,window.skcsagetSD&&window.skcsagetSD(document.body,window,document,navigator)}}else window.skcsagetSD&&window.skcsagetSD(document.body,window,document,navigator)};window.skcsatmoPoll=function(){var a=l.skcsalstActv,d=
l.skcsaidl,c=(new Date).valueOf();-1!=a&&c-a>d&&window.skcsadoReInit&&window.skcsadoReInit();window.setTimeout(window.skcsatmoPoll,1E4)};0===window.location.href.indexOf("file://")&&window.skcsatmoPoll();window.skcsajsInsertAlreadyLoaded=!1;l.skcsagetSD=function(g,d,n){function b(a,h,b){if(!h&&0!==h&&!1!==h)return b;h=c(h);b.length+a.length+h.length<=E&&(b=b+a+h);return b}function l(a,h,b,d,c,e,f){return a.length+b.length+d.length+c.length+h.length+e.length+f.length+
3+20<=E?!0:!1}function p(a,h){try{a||(a="");var b=a.split("_");if(5>b.length){var d=(new Date).valueOf();return h.sessionNumber+"_"+d+"_"+d+"_"+h.loadBalancerId+"_"+h.sessionKey}b[0]=h.sessionNumber;b[3]=h.loadBalancerId;b[4]=h.sessionKey;return b.join("_")}catch(c){return a}}function r(a,b){return b&&b.uvt?b.uvt:""}function y(a){var h="",h=window.skcsaisCorsPermitted()&&"1"==window.skcsauseJsonFormatForInitialCorsRequest?""+a+"/"+A+"/handler9/session.json?":""+a+"/"+A+"/handler9/session.js?";
a=e();window.skcsaappSessionObject?((a=window.skcsaappSessionObject)&&u&&(u.sessionInfo="x"+a.sessionNumber+"_"+a.loadBalancerId,u.loadBalancerID=a.loadBalancerId,u.sessionKey=a.sessionKey,u.sessionCookieVal=p(u.sessionCookieVal,a),persistedValFromAppComponents=r(u.persistedCookieVal,a).split("="),2==persistedValFromAppComponents.length&&(u.persistedCookieVal=persistedValFromAppComponents[1]),A=u.loadBalancerID,B=u.sessionInfo),h=b("se=",u.sessionInfo,h),h=b("&wf=",u.sessionCookieVal,h),
h=b("&wg=",u.persistedCookieVal,h),h=b("&tz=",u.sessionKey,h)):(h=u&&u.foundSessionCookie&&!u.foundLegacyCookie?b("se=",u.sessionInfo,h):b("se=",B,h),h=b("&wf=",u.sessionCookieVal,h),h=b("&wg=",u.persistedCookieVal,h),h=b("&di=",f(),h),h=b("&tz=",a,h));var g=window.skcsaconsent,h=b("&us=",g,h),h=b("&sj=","skcsa",h),h=b("&aP=",d.skcsawindowID,h),h=b("&bd=",navigator.cookieEnabled,h),h=b("&si=",navigator.javaEnabled(),h),h=b("&aM=",Q(d),h);a=L();-2<a&&(h=b("&aO=",""+a,h));h=b("&vb=",
d.skcsacompatVersion,h);h=b("&wa=","8.19.19290",h);try{h=d.top.name?b("&aW=",d.top.name,h):b("&aW=",d.skcsawindowID,h)}catch(m){}a="not_available";try{a=d==d.top}catch(m){}h=b("&bu=",a,h);a=d.skcsagC(T);if(window.skcsaappSessionObject){for(var q=a.celebrusCookies.split("; "),k=!1,t=!1,x=!1,w=0,V=q.length;w<V;w++){var v=q[w].split("=");2==v.length&&("skcsasession"==v[0]||"usy46gabsosd"==v[0]?(q[w]="skcsasession="+p(v[1],window.skcsaappSessionObject),k=!0):"skcsapersisted"==
v[0]?(q[w]=r(v[1],window.skcsaappSessionObject),t=!0):"skcsaP3P"==v[0]&&(q[w]="skcsaP3P="+g,x=!0))}k||(q[q.length]=p("",window.skcsaappSessionObject));t||(q[q.length]=r("",window.skcsaappSessionObject));x||(q[q.length]="skcsaP3P="+g);g=q.join("; ");a.celebrusCookies=g}k=a.siteCookies;g=c(a.celebrusCookies);if(h.length<E){q=[];q[0]=n.title;q[1]=k;q[2]=n.referrer;q[3]=location.href;(q[4]=d.skcsaPageID)||0===d.skcsaPageID||(q[4]="");for(t=k=!1;!l(h,c(q[0]),c(q[1]),
c(q[2]),c(q[3]),c(q[4]),g)&&!k;)k=0,c(q[1]).length>c(q[k]).length&&(k=1),c(q[2]).length>c(q[k]).length&&(k=2),c(q[3]).length>c(q[k]).length&&(k=3),c(q[4]).length>c(q[k]).length&&(k=4),q[k]=q[k].substring(0,Math.min(q[k].length/2,E-h.length-20)),t=!0,k=0===q[0].length&&0===q[1].length&&0===q[2].length&&0===q[3].length&&0===q[4].length;h=b("&cf=",q[0],h);h=b("&az=",a.celebrusCookies+"; "+q[1],h);h=b("&ar=",q[2],h);h=b("&au=",q[3],h);h=b("&sg=",q[4],h);t&&(h=b("&ic=","true",h))}return h}function v(){for(var a=
t(),b=0;a&&50>b;)if(0==a.indexOf("reinit:"))a=t(),b++;else return a;return null}function z(){var a,b;if(b=v()){J(b,":https")&&!H&&(H=!0,C=N);w();window.CelebrusLoggingUtils&&window.CelebrusLoggingUtils.logEventQueued(strEvt);a="";for(var d=0;b&&50>d;){a="";for(var c=x(b),e=0;b&&a.length+c.length<E&&50>e;)a=a+c+"&a=2",b=v(),J(b,":https")&&!H&&(H=!0,C=N),b&&(w(),c=x(b)),e++;b&&(c="https://cxa.skfh.com.tw",H||(c="http://cxa.skfh.com.tw"),resourcePath="1"==skcsauseJsonFormatForInitialCorsRequest?"/AEZ32ZHD01MJ/jsEvent.json?":
"/AEZ32ZHD01MJ/jsEvent.js?",c=c+resourcePath+"z="+a.substring(4),S(c));d++}window.skcsaLC(C+"&ipe="+a,"skcsaloadPageId")}else window.skcsaLC(C,"skcsaloadPageId")}function G(a,b,c,e,f,g,k,m){D=window.skcsagPr();(a=n.cookie)||(a="");if(""==a&&window.sessionStorage){try{(a=window.sessionStorage.getItem("usy46gabsosd"))||(a="");c=b="";window.localStorage&&(b=window.localStorage.getItem("skcsaDBID"),c=window.localStorage.getItem("skcsauvt"));var l=window.sessionStorage.getItem("skcsakey");
a=a?"usy46gabsosd="+a:"";b&&(a+="; skcsaDBID="+b);c&&(a+="; skcsauvt="+c);l&&(a+="; skcsakey="+l)}catch(p){}T=a}a.length>O&&a.substring(0,O);if(u.foundLegacyCookie||u.foundSessionCookie)u.foundLegacyCookie&&!u.sessionCookieVal&&(b=a.indexOf("usy46gabsosd"),l=a.indexOf(";",b),-1==l&&(l=a.length),l=a.substring(b,l),c="skcsa__",e=l.indexOf(c),-1<e?(b=l.indexOf("::",e),0>b&&(b=l.indexOf(";",e)),0>b&&(b=l.length),B="x"+l.substring(e+c.length,b)):(c="skcsa_",e=l.indexOf(c),-1<e?(e+=c.length-
1,b=l.indexOf("::",e),0>b&&(b=l.indexOf(";",e)),0>b&&(b=l.length),B=l.substring(e,b)):(l=a.indexOf("usy46gabsosd="),b=a.indexOf(";",l),0>b&&(b=a.length),B=d.skcsawindowID+A,d.skcsaSC(a.substring(l,b)+"::skcsa"+d.skcsawindowID+A))));else{d.skcsaSC("usy46gabsosd=skcsa"+d.skcsawindowID+A);B=d.skcsawindowID+A;try{d.top.name||(d.top.name=d.skcsawindowID)}catch(p){}}I=y("http://cxa.skfh.com.tw");N=y("https://cxa.skfh.com.tw");C=H?N:I;!d.skcsaSF&&C.length<=E&&(window.CelebrusLoggingUtils&&window.CelebrusLoggingUtils.logConfigurationSent(C),
window.skcsaisCorsPermitted()?window.skcsasendScriptRequests(C,D,z,window.skcsaprocessAppResponse):window.skcsasendScriptRequests(C,D,"",window.skcsaprocessAppResponse));d.skcsaae()}function L(a,b,c){if(P){a=P(d);try{if(!a||!a.frames)return-1;b=a.frames;for(c=0;c<b.length;c++)if(b[c]==d)return c}catch(e){}}return-1}u=a();F=k();var E=1940,O=1024,C="",D="",N="",I="";window.skcsaisCorsPermitted()&&(E=51200,O*=4);g=window;var M;M=window.skcsaappSessionObject&&window.skcsaappConsent?
window.skcsaappConsent:window.skcsafindCookieVal("skcsaP3P",1);g.skcsaconsent=M;var H="https://cxa.skfh.com.tw"==window.skcsagPr();window.skcsaprocessAppResponse=function(a,b,c,d){if(d!=window.skcsawindowId)for(var e=window.frames,f=0;f<e.length;f++)try{e[f].window.skcsaprocessAppResponse&&e[f].window.skcsaprocessAppResponse(a,b,c,d)}catch(g){}else window.skcsaisCorsPermitted()&&"1"==window.skcsauseJsonFormatForInitialCorsRequest?a&&window.skcsaexecuteJsonResponse(a,
c):window.skcsadynamicCreateScript(b,"",a)};d.skcsaGPWID=function(a,b){if(!P)return"not_available";(b=P(a))||(b=a);try{return b.skcsawindowID}catch(c){return"not_available"}};var P=d.skcsaGP,Q=d.skcsaGPWID;d.skcsaTm=(new Date).valueOf();R?G():K(G)};var M=window.skcsainitialExecutionCanProceed();!M&&window.skcsafindCookieVal("skcsaSF")?window.skcsaperiodicAssessShutdownState():(M||window.SpeedTrapComponent)&&l.skcsagetSD(D.body,l,D)}};
window.skcsasendScriptRequests=function(a,k,f,e){window.CelebrusLoggingUtils&&window.CelebrusLoggingUtils.isDryRun()?window.CelebrusLoggingUtils.executeResponseForDryRun():(window.sessionStorage&&f?f():window.skcsaLC(a,"skcsaloadPageId"),window.skcsajsInsertAlreadyLoaded||(window.skcsaLC(""+k+"/JavascriptInsert.js","skcsacsaId"),window.skcsajsInsertAlreadyLoaded=!0))};
window.skcsacookieAllowsScriptToProceed=function(a){return-1<a.indexOf("skcsaSF=")?!1:!0};function skcsaStart(){function a(a){k&&(window.skcsaSL&&window.skcsaSL(),k=!1)}var k=!1;"prerender"==document.webkitVisibilityState||document.hidden?(k=!0,document.addEventListener&&(document.addEventListener("webkitvisibilitychange",a,!1),document.addEventListener("visibilitychange",a,!1))):window.skcsaSL&&window.skcsaSL()}
window.skcsaonInitialSessionInformationResponse=function(a,k,f){if(f!=window.skcsawindowId){for(var e=window.frames,c=0;c<e.length;c++)try{if(e[c].window.skcsaonInitialSessionInformationResponse&&e[c].window.skcsaonInitialSessionInformationResponse(a,k,f))return!0}catch(p){}return!1}try{e=window.skcsaawaitingAppResponse=!1;f="";if(a){try{f=JSON.parse(a)}catch(p){}f&&(window.skcsaappSessionObject&&(f.sessionNumber!=window.skcsaappSessionObject.sessionNumber||window.skcsawid)&&
(e=!0),window.skcsaappSessionObject=f)}window.skcsaappConsent=k}catch(p){window.skcsaappSessionObject=""}e?window.skcsagetSD&&window.skcsagetSD(document.body,window,document,navigator):skcsaStart();return!0};
window.skcsaSC||(window.skcsaSC=function(a,k,f,e,c,p,g,r){var n=document,y=window,z="file:"==location.protocol;e=a+"; path=/;";var w=a.split("=");if(y.skcsauSC){if("http:"==location.protocol)return;e+=" secure;"}if(!z){var v=e;k&&(e=e+"expires="+k);";"==e.charAt(e.length-1)&&(e=e.substring(0,e.length-1));y.skcsaGD&&(n.cookie=e+y.skcsaGD());if(!r&&-1<n.cookie.indexOf(a)&&!k)return;f=location.hostname;c=f.split(".");if(g){n.cookie=e+";domain="+g;return}if(2<=c.length){p=c.length-
2;g="."+c[p+1];do if(g="."+c[p]+g,n.cookie=e+"; domain="+g,p--,r)try{if(-1==document.cookie.indexOf(w[0]+"="))return}catch(x){}while((r&&-1<n.cookie.indexOf(w[0]+"=")||!r&&-1==n.cookie.indexOf(a))&&0<=p);if(!r&&-1==n.cookie.indexOf(a)&&v)for(p=c.length-2,g="."+c[p+1];-1==n.cookie.indexOf(a)&&0<=p;)g="."+c[p]+g,n.cookie=v+" domain="+g,p--}0!==location.href.indexOf("file://")&&(r&&-1<n.cookie.indexOf(a)||!r&&-1==n.cookie.indexOf(a))&&(r?(f=new Date,f.setFullYear(1970),n.cookie=v+" domain="+location.hostname+
"; expires="+f.toGMTString()):n.cookie=v+" domain="+location.hostname)}if(z||!r&&-1==n.cookie.indexOf(a)){a=a.split("=");try{var t=window.sessionStorage;k&&(t=window.localStorage);t&&(a[1]&&-1<a[1].indexOf(";")&&(a[1]=a[1].substring(0,a[1].indexOf(";"))),r?t.removeItem(a[0]):t.setItem(a[0],a[1]));return}catch(x){}y.skcsaSF=1}});
window.skcsafindCookieVal=function(a,k){if(document.cookie)for(var f=document.cookie.split("; "),e=0;e<f.length;e++){var c=f[e].split("=");try{if(c[0]==a)return c[1]}catch(g){}}f="";try{var p=window.sessionStorage;if(k||"skcsauvt"==a||"skcsaDBID"==a||"skcsapersisted"==a)p=window.localStorage;p&&(f=p.getItem(a))}catch(g){}return f};
window.skcsadeleteLegacyCookies=function(){var a=!0,k=skcsafindCookieVal("usy46gabsosd",!1);k&&1<k.split("::").length&&(a=!1);if(document.cookie)window.skcsaSC&&(a&&window.skcsadoDeleteCookie("usy46gabsosd"),window.skcsadoDeleteCookie("skcsauvt"),window.skcsadoDeleteCookie("skcsakey"),window.skcsadoDeleteCookie("skcsaDBID"));else try{window.sessionStorage&&(a&&window.sessionStorage.removeItem("usy46gabsosd"),window.sessionStorage.removeItem("skcsakey")),
window.localStorage&&(window.localStorage.removeItem("skcsauvt"),window.localStorage.removeItem("skcsaDBID"))}catch(f){}};window.skcsadoDeleteCookie=function(a,k){var f=new Date;f.setFullYear(1970);window.skcsaSC&&window.skcsaSC(a+"=0",f.toGMTString(),"","","","",k,!0)};function skcsasessionset(a){skcsaSC("skcsasession="+a)}
function skcsapersisted(a,k,f,e,c,p,g,r,n,y){var z=new Date,w,v=0,t;a:{var x=document.cookie;""==x&&window.localStorage&&(x=(x=window.localStorage.getItem("skcsapersisted"))?"skcsapersisted="+x:"");x=x.split("; ");t=0;for(var J=x.length;t<J;t++){var K=x[t].split("=");if(1<K.length&&c==K[0]){t=unescape(K[1]);break a}}t=null}g&&(v=g);x=!0;t&&(t=t.split("_"),7<=t.length&&(e==t[4]&&(x=!1),t[2]&&(w=t[2],r=t[3],v=t[6])));x&&(g||v++);w||(w=f);z.setTime(z.getTime()+p);y?skcsaSC(c+"="+
a+"_"+k+"_"+w+"_"+r+"_"+e+"_"+n+"_"+v,z.toGMTString()):skcsaSC(c+"="+a+"_"+k+"_____",z.toGMTString())}
function skcsalegacyset(a,k,f,e){var c=window,p=document.cookie;c.skcsaGD&&c.skcsaGD();var g=p.indexOf("usy46gabsosd"),r="";if(-1==g)window.skcsaSC&&window.skcsaSC("usy46gabsosd=skcsa__"+a+"_"+k+"_"+f+e);else{var r=p.indexOf(";",g),n=c="";0>r&&(r=p.length);p=p.substring(g+12+1,r);g=p.indexOf("skcsa");-1<g?(c=p.substring(0,g),""!=c&&(c="::"+c),g=p.indexOf("::",g),-1<g&&(n=""==c?p.substring(g):p.substring(g+2))):c="::"+p;r="usy46gabsosd=skcsa__"+a+"_"+k+"_"+f+
e;""!=c&&(r+=c);""!=n&&(r+=n);window.skcsaSC&&window.skcsaSC(r)}}function skcsakeyset(a,k){skcsaSC("skcsakey="+a)}function skcsaDBIDset(a,k){var f=new Date;f.setTime(f.getTime()+k);skcsaSC("skcsaDBID="+a,f.toGMTString())}
function skcsauvt(a,k,f,e,c){var p=new Date,g,r=0,n;a:{n=document.cookie;""==n&&window.localStorage&&(n=(n=window.localStorage.getItem("skcsauvt"))?"skcsauvt="+n:"");n=n.split("; ");for(var y=0,z=n.length;y<z;y++){var w=n[y].split("=");if(1<w.length&&"skcsauvt"==w[0]){n=unescape(w[1]);break a}}n=null}if(n&&(n=n.split("_"),5<=n.length)){if(k==n[2])return;g=n[0];e=n[1];r=n[4]}r++;g||(g=a);p.setTime(p.getTime()+f);skcsaSC("skcsauvt="+g+"_"+e+"_"+k+"_"+c+"_"+r,p.toGMTString())}
function skcsasetShutdown(){window.skcsadeleteSessionCookie&&window.skcsadeleteSessionCookie();var a=(new Date).valueOf();if(window.skcsaGD){var k=window.skcsaGD();document.cookie="skcsaSF="+a+";path=/"+k}else window.skcsaSC&&window.skcsaSC("skcsaSF="+a)}
function skcsaGo(){try{var a=window.crypto||window.msCrypto;window.skcsagenerateUUID=function(){return"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx".replace(/[x]/g,function(a){return(16*Math.random()|0).toString(16)})};"undefined"!=typeof a&&"undefined"!=typeof a.getRandomValues&&(window.skcsagenerateUUID=function(){var f=new Uint16Array(8);a.getRandomValues(f);var e=function(a){for(a=a.toString(16);4>a.length;)a="0"+a;return a};return""+e(f[0])+e(f[1])+e(f[2])+e(f[3])+e(f[4])+e(f[5])+e(f[6])+
e(f[7])});window.skcsawindowId="_"+(new Date).getTime()+"0."+window.skcsagenerateUUID()+"_";if(window.skcsaAppBridgeV2){window.skcsaawaitingAppResponse=!0;try{var k=window.skcsafindCookieVal("skcsapersisted",!0);window.skcsaAppBridgeV2.requestSessionInformation(location.href,k,window.skcsawindowId,!0)}catch(f){window.skcsaappSessionObject="",window.skcsaawaitingAppResponse=!1,skcsaStart()}}else window.skcsaawaitingAppResponse=!1,skcsaStart()}catch(f){}}
skcsaGo();
window.skcsaRTEHandler={maxWaitDurationMillis:1E4,maxActionProcessDurationMillisToAllowRequeue:50,targetMissingPollingDurationMillis:250,domContentReadyPollingDurationMillis:100,injectionCount:0,staleCount:0,rejectedCount:0,errorCount:0,nameVal:"RTEHandler",currentActionID:"",currentRuleID:"",currentContentID:"",currentCustomID:"",queue:[],isDomContentReady:function(){var a=document.getElementsByTagName("body");return a&&0!==a.length?"complete"==document.readyState||"loaded"==document.readyState||
"interactive"==document.readyState?!0:!1:!1},reset:function(){this.queue=[];this.errorCount=this.rejectedCount=this.staleCount=this.injectionCount=0},getTimestampMillis:function(){return(new Date).getTime()},handleResponse:function(a,c){if(!a||!a.length||!c&&-1<document.cookie.indexOf("skcsaSF=y"))return 0;var b=this.getTimestampMillis(),d,e,f;d=0;for(e=a.length;d<e;d++){f=a[d];try{f.queueTimestampMillis=b;if(f.content&&(f.content=this.doUnescape(f.content),f.parsedContent=this.parseContent(f.content),
!f.parsedContent)){this.rejectedCount++;continue}f.externalContentId&&(f.externalContentId=this.doUnescape(f.externalContentId));f.replacementurl&&(f.replacementurl=this.doUnescape(f.replacementurl));f.idValue&&(f.idValue=this.doUnescape(f.idValue));this.validVariables(f.csaNumber,f.contentKey)?f.csaCallbackTime?this.doCallback(f):this.queueAction(f):this.distributeActionToChildCsas(f)||this.queueAction(f)}catch(g){this.rejectedCount++,this.handleError(g)}}return this.processQueue()},doCallback:function(a){window.skcsadCB?
window.skcsadCB(parseInt(a.csaCallbackTime),this.getTimestampMillis()):(window.skcsadCBValTS=this.getTimestampMillis(),window.skcsadCBVal=parseInt(a.csaCallbackTime))},queueAction:function(a){this.queue.unshift(a)},isOlderThan:function(a,c){var b=this.getTimestampMillis();return Math.abs(b-c)>a},isActionStale:function(a){return this.isOlderThan(this.maxWaitDurationMillis,a.queueTimestampMillis)},processQueue:function(){if(0===this.queue.length)return 0;if(!this.isDomContentReady()){var a=
this;window.setTimeout(function(){a.processQueue.call(a)},this.domContentReadyPollingDurationMillis);return 0}var c=0,b;for(b=this.queue.length-1;0<=b;b--){var d=this.queue[b];try{if(this.isActionStale(d))this.staleCount++,this.queue.splice(b,1);else{var e=this.getTimestampMillis();this.processAction(d)?(this.injectionCount++,this.queue.splice(b,1),this.actionsExecutedCount++,c++):this.isOlderThan(this.maxActionProcessDurationMillisToAllowRequeue,e)&&(this.rejectedCount++,this.queue.splice(b,1))}}catch(f){this.queue.splice(b,
1),this.handleError(f)}}0<this.queue.length&&(a=this,window.setTimeout(function(){a.processQueue.call(a)},this.targetMissingPollingDurationMillis));return c},processAction:function(a){return this.validVariables(a.csaNumber,a.contentKey)?(this.currentActionID=a.actionID,this.currentRuleID=a.ruleID,this.currentContentID=a.contentID,this.currentCustomID=a.customID,a=this.updateContent(a),this.currentCustomID=this.currentContentID=this.currentRuleID=this.currentActionID="",a):this.distributeActionToChildCsas(a)},
validVariables:function(a,c){return window.skcsawid!=a||c&&c!=window.skcsacontentKey?!1:!0},isObjectInArray:function(a,c){if(!c||!a)return!1;for(var b=0,d=c.length;b<d;b++)if(c[b]===a)return!0;return!1},recurseChildCsas:function(a,c,b){var d=-1;try{d=a.skcsawid}catch(f){return!1}if(d==c.csaNumber){if(a.skcsaRTEHandler)return c.csaCallbackTime&&a.skcsaRTEHandler.doCallback(c),a.skcsaRTEHandler.queueAction(c),this.isObjectInArray(a,b)||b.push(a),!0}else try{if(a.frames&&
0<a.frames.length)for(var d=0,e=a.frames.length;d<e;d++)if(this.recurseChildCsas(a.frames[d],c,b))return!0}catch(f){}return!1},distributeActionToChildCsas:function(a){if(window.skcsagHW){var c=[];a=this.recurseChildCsas(window.skcsagHW(),a,c);if(0<c.length)for(var b=0,d=c.length;b<d;b++)c[b].skcsaRTEHandler.processQueue();return a}return!1},insertNodeAfter:function(a,c){var b=c.parentNode;b.lastchild==c?b.appendChild(a):b.insertBefore(a,c.nextSibling)},getParentElement:function(a){return a.parentElement?
a.parentElement:a.parentNode?a.parentNode:""},replaceImage:function(a,c,b){if(b){for(var d=!1,e=a;a&&!d;){if(a.href&&("a"==(""+a.tagName).toLowerCase()||"area"==(""+a.tagName).toLowerCase())){a.href=b;d=!0;break}var f=this.getParentElement(a);if(a===f)break;a=f}if(d)e.src=c;else if(a=document.createElement("SPAN"),d=document.createElement("A"),d.href=b,a.appendChild(d),b=this.getParentElement(e))b.replaceChild(a,e),d.appendChild(e),e.src=c,e.setAttribute("style","border-style: none")}else a.src=c},
doUnescape:function(a){window.decodeURIComponent||(a=a.replace(/%C2%A3/g,"%A3"));a=a.replace(/\\+/g,"%20");return a=window.decodeURIComponent?window.decodeURIComponent(a):unescape(a)},pushContentAddedData:function(a){this.currentActionID&&(window.skcsavariableStateChange?window.skcsareportContentAction(this.currentActionID,this.currentRuleID,this.currentContentID,this.currentCustomID):(window.skcsaContentIdArray||(window.skcsaContentIdArray=[]),window.skcsaContentIdArray[window.skcsaContentIdArray.length]=
{actionId:this.currentActionID,ruleId:this.currentRuleID,contentId:this.currentContentID,customId:this.currentCustomID}))},getFormName:function(a){if(!a)return"";var c=a.getAttribute("name");return c?c:a.name&&!a.name.type?a.name:""},getFormID:function(a){if(!a)return"";var c=a.getAttribute("id");return c?c:a.id&&!a.id.type?a.id:""},getElementClass:function(a){var c=a.getAttribute("class");c||(c=a.getAttribute("className"));return c},findMatchesByParentFormName:function(a,c,b){var d=new RegExp(c);
a||(a=document.getElementsByTagName("*"));for(var e=[],f=0,g=a.length;f<g;f++)if(a[f].form){var h=this.getFormName(a[f].form);b?d.test(h)&&(e[e.length]=a[f]):c==h&&(e[e.length]=a[f])}return e},findMatchesByParentFormID:function(a,c,b){var d=new RegExp(c);a||(a=document.getElementsByTagName("*"));for(var e=[],f=0,g=a.length;f<g;f++)if(a[f].form){var h=this.getFormID(a[f].form);b?d.test(h)&&(e[e.length]=a[f]):c==h&&(e[e.length]=a[f])}return e},findMatchesByName:function(a,c,b){a||(a=document.getElementsByTagName("*"));
var d=[];if(b)for(c=new RegExp(c),b=0;b<a.length;b++)c.test(a[b].name)&&(d[d.length]=a[b]);else for(c=c?c.toLowerCase():c,b=0;b<a.length;b++){var e=(""+a[b].name).toLowerCase();c==e&&(d[d.length]=a[b])}return d},findMatchesById:function(a,c,b){a||(a=document.getElementsByTagName("*"));var d=[];if(b)for(c=new RegExp(c),b=0;b<a.length;b++)c.test(a[b].id)&&(d[d.length]=a[b]);else for(b=0;b<a.length;b++)c==a[b].id&&(d[d.length]=a[b]);return d},findMatchesByClass:function(a,c,b){a||(a=document.getElementsByTagName("*"));
var d=[];if(b)for(c=new RegExp(c),b=0;b<a.length;b++)c.test(this.getElementClass(a[b]))&&(d[d.length]=a[b]);else for(b=0;b<a.length;b++)c==this.getElementClass(a[b])&&(d[d.length]=a[b]);return d},findMatchesByHref:function(a,c,b){a||(a=document.getElementsByTagName("A"));var d=[];if(b)for(c=new RegExp(c),b=0;b<a.length;b++)c.test(a[b].href)&&(d[d.length]=a[b]);else for(c=c.toLowerCase(),b=0;b<a.length;b++){var e=(""+a[b].href).toLowerCase();c==e&&(d[d.length]=a[b])}return d},findMatchesBySrc:function(a,
c,b){a||(a=document.getElementsByTagName("IMG"));var d=[];if(b)for(c=new RegExp(c),b=0;b<a.length;b++)c.test(a[b].src)&&(d[d.length]=a[b]);else for(c=c.toLowerCase(),b=0;b<a.length;b++){var e=(""+a[b].src).toLowerCase();c==e&&(d[d.length]=a[b])}return d},findMatchesByTagName:function(a,c,b){c=c.toUpperCase();a||(a=document.getElementsByTagName("*"));var d=[];if(b)for(c=new RegExp(c),b=0;b<a.length;b++)c.test((""+a[b].tagName).toUpperCase())&&(d[d.length]=a[b]);else for(b=0;b<a.length;b++){var e=(""+
a[b].tagName).toUpperCase();c==e&&(d[d.length]=a[b])}return d},findMatchesByType:function(a,c,b){c=c.toLowerCase();a||(a=document.getElementsByTagName("*"));var d=[];if(b)for(c=new RegExp(c),b=0;b<a.length;b++)c.test((""+a[b].type).toLowerCase())&&(d[d.length]=a[b]);else for(b=0;b<a.length;b++){var e=(""+a[b].type).toLowerCase();c==e&&(d[d.length]=a[b])}return d},updateContent:function(a){"undefined"!=typeof SpeedTrapComponent&&SpeedTrapComponent.logMessage("Inserting "+a.parsedContent);if(3==a.csaAction)return this.insertContentAtTopOfPage(a.parsedContent),
!0;if(4==a.csaAction)return this.insertContentAtEndOfPage(a.parsedContent),!0;if(!a.attributesArray)return!1;for(var c=!1,b=null,d="",e="",f="",g="",h="",p="",k=0,q=a.attributesArray.length;k<q;k++){var l=a.attributesArray[k].attributeType,m=a.attributesArray[k].attributeValue,n=a.attributesArray[k].attributeIsRegEx;"NAME"==l?b=this.findMatchesByName(b,m,n):"ID"==l?b=this.findMatchesById(b,m,n):"CLASS"==l?b=this.findMatchesByClass(b,m,n):"IMAGE"==l?(d={val:m,isRegex:n},c=!0):"ANCHOR"==l?e={val:m,
isRegex:n}:"TAGNAME"==l?f={val:m,isRegex:n}:"FORM_NAME"==l?g={val:m,isRegex:n}:"FORM_ID"==l?h={val:m,isRegex:n}:"TYPE"==l&&(p={val:m,isRegex:n})}g&&(b=this.findMatchesByParentFormName(b,g.val,g.isRegex));h&&(b=this.findMatchesByParentFormID(b,h.val,h.isRegex));e&&(b=this.findMatchesByHref(b,e.val,e.isRegex));d&&(b=this.findMatchesBySrc(b,d.val,d.isRegex));f&&(b=this.findMatchesByTagName(b,f.val,f.isRegex));p&&(b=this.findMatchesByType(b,p.val,p.isRegex));if(null===b)return!1;e=!1;for(k=0;k<b.length;k++)d=
b[k],f=(""+b[k].tagName).toUpperCase(),"HEAD"!=f&&"META"!=f&&(c&&"IMAGE"==a.replacementContentType?(0==a.csaAction?(this.replaceImage(d,a.parsedContent.childNodes[0].nodeValue,a.replacementurl),this.tagContent(d)):1==a.csaAction?(e=this.toInnerHtmlNode(a.parsedContent.childNodes[0]),(f=d.parentNode)&&f.insertBefore(e,d)):2==a.csaAction&&(e=this.toInnerHtmlNode(a.parsedContent.childNodes[0]),this.insertNodeAfter(e,d)),e=!0):(e=!0,this.modifyTarget(d,a)),this.pushContentAddedData());return e},insertContentAtTopOfPage:function(a){var c=
document.createElement("SPAN");this.tagContent(c);var b=document.getElementsByTagName("body")[0];b&&(b.insertBefore(c,b.firstChild),this.appendToDoc(c,a),this.pushContentAddedData())},insertContentAtEndOfPage:function(a){var c=document.createElement("SPAN");this.tagContent(c);var b=document.getElementsByTagName("body")[0];b&&(b.appendChild(c),this.appendToDoc(c,a),this.pushContentAddedData())},modifyTarget:function(a,c){if(a){var b=document.createElement("SPAN");this.tagContent(b);var d=a.parentNode;
0==c.csaAction?d&&d.replaceChild(b,a):1==c.csaAction?d&&d.insertBefore(b,a):2==c.csaAction&&this.insertNodeAfter(b,a);this.appendToDoc(b,c.parsedContent)}},parseContent:function(a){if(window.DOMParser)a=(new DOMParser).parseFromString(a,"text/xml");else{var c=new ActiveXObject("Microsoft.XMLDOM");c.async="false";c.loadXML(a);a=c}a=a.getElementsByTagName("strtecontent");return 1==a.length?a[0]:null},getHeadReference:function(){var a=document.getElementsByTagName("HEAD");return 0<a.length?a[0]:null},
appendToDoc:function(a,c){var b=null,d=c.nodeName.toUpperCase();if("STRTECONTENT"==d)b=a;else if("HEAD"==d){var e=this.getHeadReference();if(e){for(d=0;d<c.childNodes.length;d++)this.appendToDoc(e,c.childNodes[d]);return}}else if(b=this.createNewNode(c,a),null===b)return;e=0===d.indexOf("FB");if("SCRIPT"!=d&&"NOSCRIPT"!=d&&"STYLE"!=d&&"OBJECT"!=d&&"TABLE"!=d&&"H1"!=d&&"H2"!=d&&"H3"!=d&&"H4"!=d&&"H5"!=d&&"H6"!=d&&!e)for(d=0;d<c.childNodes.length;d++)this.appendToDoc(b,c.childNodes[d])},createNewNode:function(a,
c){var b;if(3==a.nodeType)b=document.createTextNode(a.nodeValue),c.appendChild(b);else{if(1==a.nodeType){b=a.nodeName.toUpperCase();var d=0===b.indexOf("FB");"OBJECT"==b||"TABLE"==b||"H1"==b||"H2"==b||"H3"==b||"H4"==b||"H5"==b||"H6"==b||d?(b=this.createObjectNode(a),c.appendChild(b)):"SCRIPT"==b?b=this.createScriptNode(a,c):"NOSCRIPT"==b?(b=this.createNoScriptNode(a),c.appendChild(b)):"STYLE"==b?b=this.createStyleNode(a,c):(b=document.createElement(a.nodeName.toUpperCase()),this.copyAttributes(a,
b),c.appendChild(b));return b}return null}},createObjectNode:function(a){return this.toInnerHtmlNode(a)},tagInjectedContent:function(a,c,b,d,e){a&&(c&&(a.skcsacontentActionIdentifier=c),b&&(a.skcsaruleIdentifier=b),d&&(a.skcsacontentIdentifier=d),e&&(a.skcsacustomIdentifier=e))},tagContent:function(a){this.tagInjectedContent(a,this.currentActionID,this.currentRuleID,this.currentContentID,this.currentCustomID)},toXML:function(a){return"undefined"!=typeof XMLSerializer?(new XMLSerializer).serializeToString(a):
a.xml?a.xml:""},toInnerHtmlNode:function(a){var c=document.createElement("SPAN");c.innerHTML=this.toXML(a);this.tagContent(c);return c},createScriptNode:function(a,c){var b=document.createElement("SCRIPT");c.appendChild(b);var d=a.attributes.getNamedItem("type");d&&(b.type=d.value);if(d=a.attributes.getNamedItem("src"))b.src=d.value;0<a.childNodes.length&&(b.text=a.childNodes[0].nodeValue);return b},createNoScriptNode:function(a){for(var c=document.createElement("NOSCRIPT"),b=document.createElement("SPAN"),
d=0;d<a.childNodes.length;d++)this.appendToDoc(b,a.childNodes[d]);c.text=b.innerHTML;return c},createStyleNode:function(a,c){var b=document.createElement("STYLE");c.appendChild(b);var d=a.attributes.getNamedItem("type");d&&(b.type=d.value);if(d=a.attributes.getNamedItem("src"))b.src=d.value;if(d=a.attributes.getNamedItem("media"))b.media=d.value;0<a.childNodes.length&&(b.styleSheet?b.styleSheet.cssText=a.childNodes[0].nodeValue:b.innerHTML=this.toXML(a.childNodes[0]));return b},copyAttributes:function(a,
c){for(var b=null,d=null,e=0,f=a.attributes.length;e<f;e++){var g=""+a.attributes[e].name,h=a.attributes[e].value;if("style"==g.toLowerCase())c.style.cssText=h;else if("class"==g.toLowerCase())window.attachEvent?c.className=h:c.setAttribute(g,h);else if("type"==g){b=h;continue}"value"==g?d=h:c.setAttribute(g,h)}b&&c.setAttribute("type",b);d&&(c.setAttribute("value",d),c.value=d)},handleError:function(a){this.errorCount++;if(window.SpeedTrapComponent){var c;c="There was an error.\n"+("Error description: "+
a.message+"\n");c+="Line no: "+a.lineNumber+"\n";a.stack&&(c+="Stack: "+a.stack);window.SpeedTrapComponent.logMessage("Error "+c)}}};
;