window.skbcsa2compatVersion="3";window.skbcsa2packetVersion="1";window.skbcsa2useCorsForInitialRequest="1";window.skbcsa2useJsonFormatForInitialCorsRequest="1";window.CelebrusDataPrivacy={MAY_CONTAIN_PERSONAL_DATA:1,ANONYMOUS_DATA_ONLY:2};
window.skbcsa2pPO=function(a,k){window.localStorage&&window.localStorage.setItem("skbcsa2P3P",a);var f=new Date;f.setFullYear(f.getFullYear()+20);window.skbcsa2SC("skbcsa2P3P="+a,f.toGMTString());k&&window.skbcsa2SC("skbcsa2P3P="+a,f.toGMTString(),"","","","",k,!1);"optedOut"==a&&window.skbcsa2stopEvents&&window.skbcsa2stopEvents();window.skbcsa2doReInit?window.skbcsa2doReInit():window.skbcsa2Go&&!window.skbcsa2wid&&skbcsa2Go()};
window.skbcsa2optOut=function(a){window.skbcsa2pPO("optedOut",a)};window.skbcsa2optIn=function(a){window.skbcsa2pPO("optedIn",a)};window.skbcsa2anonymous=function(a){window.skbcsa2pPO("anonymous",a)};
function skbcsa2sessionShutdownPeriodExceeded(){var a=!1,a=document.cookie?-1<document.cookie.indexOf("skbcsa2SF="):null!=window.sessionStorage.getItem("skbcsa2SF");if(!a)return!1;a=window.skbcsa2findCookieVal("skbcsa2SF");a=parseInt(a,10);return-1==a||isNaN(a)?!1:Math.abs((new Date).valueOf()-a)>10800000?!0:!1}
function skbcsa2periodicAssessShutdownState(){window.skbcsa2findCookieVal("skbcsa2SF")&&(window.skbcsa2sessionShutdownPeriodExceeded()?(window.skbcsa2doDeleteCookie&&window.skbcsa2doDeleteCookie("skbcsa2SF"),window.skbcsa2lstActv=(new Date).valueOf(),window.skbcsa2qNI=!0,window.skbcsa2findCookieVal("skbcsa2P3P",1),window.skbcsa2resetCSA&&window.skbcsa2resetCSA(),window.skbcsa2executeReInitNow&&window.skbcsa2executeReInitNow()):window.setTimeout(skbcsa2periodicAssessShutdownState,
1E4))}var skbcsa2GL=-1==document.cookie.indexOf("skbcsa2SF=")&&-1==document.cookie.indexOf("skbcsa2StopFlag=y")&&-2!=window.skbcsa2sn;window.skbcsa2pendingManualEvents||(window.skbcsa2pendingManualEvents=[]);window.skbcsa2queuedYoutubeReferences||(window.skbcsa2queuedYoutubeReferences=[]);
window.skbcsa2sn||(window.skbcsa2event=function(a){window.skbcsa2pendingManualEvents.push({eventTypeIdentifier:"basket",payload:a})},window.skbcsa2click=function(a){a&&window.skbcsa2pendingManualEvents.push({eventTypeIdentifier:"click",payload:a})},window.skbcsa2textchange=function(a){a&&window.skbcsa2pendingManualEvents.push({eventTypeIdentifier:"textchange",payload:a})},window.skbcsa2formsubmit=function(a){window.skbcsa2pendingManualEvents.push({eventTypeIdentifier:"formsubmit",
payload:a})},window.skbcsa2SendJsonData=function(a,k){window.skbcsa2pendingManualEvents.push({eventTypeIdentifier:"jsondata",payload:a,dataPrivacyVal:k})},window.skbcsa2trackYouTubeIframePlayer=function(a,k){window.skbcsa2queuedYoutubeReferences.push({playerRef:a,playerIdentifier:k})});window.skbcsa2initialExecutionCanProceed=function(){return 1==skbcsa2GL?window.skbcsa2windowID?!1:!0:!1};
window.skbcsa2blockExecutionForInsertAlreadyPresent=function(){return window.skbcsa2getSD?!0:!1};
window.skbcsa2SL=function(){function a(){l.skbcsa2windowID="_"+(new Date).getTime()+"0."+window.skbcsa2generateUUID()+"_";var m=window.skbcsa2findCookieVal("skbcsa2session"),d=window.skbcsa2findCookieVal("skbcsa2persisted"),a=window.skbcsa2findCookieVal("usy46gabsosd"),b,f,c,e,k,n=!1,p=!1;a&&(n=!0);m&&(p=!0);var g=m?m.split("_"):null;if(g&&5==g.length)b="x"+g[0]+"_"+g[3],f=g[1],c=g[2],e=g[3],k=g[4],A=e,B=b;else{for(b=""+Math.floor(9999*Math.random()+1);4>b.length;)b="0"+b;a&&
(b=A,e=window.skbcsa2findCookieVal("usy46gabsosd"))&&(g=e.lastIndexOf("_"),-1!=g&&(e=e.substring(g+1),b=4==e.length&&e.match(Q)?e:b));A=b;B=l.skbcsa2windowID+A;try{l.top.name||(l.top.name=l.skbcsa2windowID)}catch(r){}b=B;e=A}return{sessionInfo:b,lastActivityTS:f,sessionStartTS:c,loadBalancerID:e,sessionKey:k,sessionCookieVal:m,persistedCookieVal:d,legacyCookieVal:a,foundLegacyCookie:n,foundSessionCookie:p}}function k(){var m=window.skbcsa2findCookieVal("skbcsa2persisted");if(m){var d=
m.split("_");return 7!=d.length?null:{dbID:d[0],rtID:d[1],udID:d[2],acqTS:d[3],recSN:d[4],recTS:d[5],frq:d[6],cookieVal:m}}return null}function f(){if(F){var m="_";F.dbID&&(m=F.dbID+m);F.rtID&&(m+=F.rtID);return m}return window.skbcsa2findCookieVal("skbcsa2DBID",1)}function e(){return u&&u.sessionKey?u.sessionKey:window.skbcsa2findCookieVal("skbcsa2key")}function c(m){return I?(m=I(m),m=m.replace(/'/g,"%27"),m=m.replace(/~/g,"%7E")):escape(m)}function p(m){return"https:"==(""+location.protocol).toLowerCase()||
1==l.skbcsa2ForceSecure?"skbcsa2ssl"+m:"skbcsa2tcp"+m}function g(m){m=p(m);try{if(l.sessionStorage){var d=l.sessionStorage.getItem(m);if(d)return""+d}}catch(a){}return""}function r(m,d){var a=p(m);try{l.sessionStorage&&l.sessionStorage.setItem(a,d)}catch(b){}}function n(m){try{var d=g(m),a=parseInt(d);return isNaN(a)?0:a}catch(b){return 0}}function y(){return n("lastQueuePointer")}function z(m){try{var d=parseInt(g(m));isNaN(d)&&(d=0);49==d?d=0:d++;r(m,""+d)}catch(a){}}function w(){var m=
n("lastProcessPointer"),d=y();m<d&&z("lastProcessPointer")}function v(){var m=y();g(m)&&z("lastQueuePointer")}function t(){var m=n("lastProcessPointer"),d="";try{d=g(m)}catch(a){}try{var f=p(m);try{l.sessionStorage&&l.sessionStorage.removeItem(f)}catch(a){}}catch(a){}return d}function x(m){m=m.replace(/&/g,"+");m=m.replace(/%/g,"q");m=m.replace(/(..)(..)/g,"$2$1");m=m.replace(/(........)(.....)/g,"$2$1");var d=f(),a=e();a&&(d+="_"+a);return m="z="+c(d)+"&y="+m}function J(a,d){return a?-1!==a.indexOf(d,
a.length-d.length):!1}function K(a){function d(){w();b()}function f(){w();b()}function b(){var b=t();if(b)if(0==b.indexOf("reinit:"))d();else{window.CelebrusLoggingUtils&&window.CelebrusLoggingUtils.logEventQueued(b);var c;var e=R;try{var g="https://TIVMITDDDT01.SKBDev.intra.skb";J(b,":http")&&(g="http://TIVMITDDDT01.SKBDev.intra.skb");var g=g+"/"+A+"/",b=x(b),k="ZDY21YGC90LI/uw2jde932.bmp?";e&&(k="1"==skbcsa2useJsonFormatForInitialCorsRequest?"AEZ32ZHD01MJ/jsEvent.json?":"AEZ32ZHD01MJ/jsEvent.js?");c=g+k+b}catch(n){c=null}if(c)if(R)S(c,d,f);else{null==
l.skbcsa2sImgArr[0]&&(l.skbcsa2sImgArr[0]=new Image,b=l.skbcsa2sImgArr[0],b.attachEvent?b.attachEvent("onload",d):b.addEventListener&&b.addEventListener("load",d,!1),b=l.skbcsa2sImgArr[0],e=f,b.attachEvent?b.attachEvent("onerror",e):b.addEventListener&&b.addEventListener("error",e,!1));try{l.skbcsa2sImgArr[0].src=c}catch(n){f()}}else f()}else a()}l.skbcsa2sImgArr=[];b()}function G(a,d,f,b){return(d=window.skbcsa2findCookieVal(a))?a+"="+d:""}function L(a,d){""!=d&&(""!=a&&(a+=
"; "),a+=d);return a}function S(a,d,f){var b=a.indexOf("?"),c="",e="";-1==b?c=a:(c=a.substring(0,b),e=a.substring(b+1));var g=new XMLHttpRequest;g.open("POST",c,!0);g.withCredentials=!0;g.setRequestHeader("Content-Type","text/plain;charset=UTF-8");d&&(g.onload=function(){d(g)});f&&(g.onerror=function(){f(g)});try{g.send(e)}catch(k){}}if(!window.skbcsa2blockExecutionForInsertAlreadyPresent()){var l=window,D=document,U=location,T=D.cookie,A="",B="",Q=/^[a-z0-9]+$/i;l.skbcsa2LF=!0;l.skbcsa2TCP=
"http://TIVMITDDDT01.SKBDev.intra.skb";l.skbcsa2SSL="https://TIVMITDDDT01.SKBDev.intra.skb";l.skbcsa2gPr=function(a){var d=(""+U.protocol).toLowerCase();if("https:"==d)return"https://TIVMITDDDT01.SKBDev.intra.skb";a||(a=d);1==l.skbcsa2ForceSecure&&(a="https:");return"http:"==a||"http"==a?"http://TIVMITDDDT01.SKBDev.intra.skb":"https://TIVMITDDDT01.SKBDev.intra.skb"};window.skbcsa2clearStoppedState=function(){window.skbcsa2doDeleteCookie&&window.skbcsa2doDeleteCookie("skbcsa2SF")};window.skbcsa2stop=function(){window.skbcsa2deleteSessionCookie&&window.skbcsa2deleteSessionCookie();if(document.cookie)window.skbcsa2SC&&
window.skbcsa2doDeleteCookie("skbcsa2key");else try{window.sessionStorage&&window.sessionStorage.removeItem("skbcsa2key")}catch(a){}window.skbcsa2oTP=!1;window.skbcsa2SC&&window.skbcsa2SC("skbcsa2SF="+(new Date).valueOf())};var I=l.encodeURIComponent,u="",F="";window.skbcsa2cookieList=[];l.skbcsa2gC=function(a){var d="usy46gabsosd skbcsa2uvt skbcsa2DBID skbcsa2key skbcsa2session skbcsa2persisted skbcsa2P3P".split(" "),f="";if(true){for(var b=
document.cookie,c=0;c<d.length;c++){var e=G(d[c],a);e&&(f=L(f,e),b=-1<b.indexOf(e+"; ")?b.replace(e+"; ",""):-1<b.indexOf(e+";")?b.replace(e+";",""):b.replace(e,""))}return{celebrusCookies:f,siteCookies:b}}d="usy46gabsosd skbcsa2uvt skbcsa2DBID skbcsa2key skbcsa2session skbcsa2persisted skbcsa2P3P".split(" ");for(c=0;c<d.length;c++)(e=G(d[c],a))&&(f=L(f,e));d="";if(0<window.skbcsa2cookieList.length)for(b=0,c=window.skbcsa2cookieList.length;b<c;b++)(e=G(window.skbcsa2cookieList[b],
a))&&(d=L(d,e));return{celebrusCookies:f,siteCookies:d}};l.skbcsa2ae=function(){l.skbcsa2wid||((new Date).valueOf()-l.skbcsa2Tm>30000?0===l.frames.length&&window.skbcsa2doDeleteCookie&&(window.skbcsa2doDeleteCookie("usy46gabsosd"),window.skbcsa2doDeleteCookie("skbcsa2session"),l.skbcsa2SC("skbcsa2SF="+(new Date).valueOf()),skbcsa2periodicAssessShutdownState()):l.setTimeout(l.skbcsa2ae,2E3))};l.skbcsa2client_event=function(a,d){if(!(-1<document.cookie.indexOf("skbcsa2SF="))){var c=
window;c.skbcsa2queueUserEvent?c.skbcsa2queueUserEvent(a,d):c.setTimeout("skbcsa2client_event('"+a+"','"+d+"');",500)}};l.skbcsa2GP=function(a){return null};l.skbcsa2GPWID=function(a){return a.skbcsa2windowID};l.skbcsa2executeJsonResponse=function(a,d){var c=a,b=window.skbcsa2wid;d||(c=JSON.parse(a));var f=c.windowVariables,e;for(e in f)0===e.indexOf("skbcsa2")&&(window[e]="skbcsa2uSC"==e||"skbcsa2useCors"==e||"skbcsa2doCapture"==e||"skbcsa2lookups"==e||"skbcsa2useJsonFormatRequest"==
e?"true"==f[e]:"skbcsa2idl"==e||"skbcsa2sST"==e||"skbcsa2mST"==e?parseInt(f[e],10):f[e]);if(f=c.queueNavigatorInfo)window.skbcsa2qNI=f;if(c.isExcludedFromSample&&skbcsa2setShutdown)skbcsa2setShutdown();else{(f=c.isMinimalCookieFormat)?(window.skbcsa2deleteLegacyCookies&&window.skbcsa2deleteLegacyCookies(),skbcsa2sessionset(c.sessionCookieValue)):(skbcsa2legacyset(c.sn,c.lastActivityTs,c.sessionStartTs,c.lbId),skbcsa2keyset(c.sessionKey));window.skbcsa2doCelebrusInsertInvocation&&
window.skbcsa2doCelebrusInsertInvocation(b);if(b=c.persistedCookieValues)f?skbcsa2persisted(b.dbID,b.rtId,b.acq,b.sn,b.cookieName,b.cookieExpiry,b.frq,b.acqTS,b.recTS,b.trackDevices):(b.trackDevices?skbcsa2uvt(b.acq,b.sn,b.cookieExpiry,b.acqTS,b.recTS):skbcsa2doDeleteCookie&&skbcsa2doDeleteCookie("skbcsa2uvt"),skbcsa2doDeleteCookie&&skbcsa2doDeleteCookie("skbcsa2DBID"),skbcsa2DBIDset(b.dbID+"_"+b.rtId,b.cookieExpiry));if(c.contentResponse&&window.skbcsa2RTEHandler){b=
[];try{b=JSON.parse(c.contentResponse)}catch(g){}try{window.skbcsa2RTEHandler.handleResponse(b)}catch(g){}}}};l.skbcsa2dynamicCreateScript=function(a,d,c){var b=document;if(b.getElementById){var e=b.getElementsByTagName("head").item(0);e&&(b=b.createElement("SCRIPT"),b.type="text/javascript",b.id=a,d&&(b.src=d),c&&(b.text=c),e.appendChild(b))}};l.skbcsa2LC=function(a,d){"skbcsa2csaId"!=d&&window.skbcsa2isCorsPermitted()?S(a,function(a){200===a.status&&(a=a.responseText,window.skbcsa2isCorsPermitted()&&
"1"==window.skbcsa2useJsonFormatForInitialCorsRequest?a&&window.skbcsa2executeJsonResponse(a):window.skbcsa2dynamicCreateScript(d,"",a))},null):window.skbcsa2dynamicCreateScript(d,a,"")};window.skbcsa2isCorsPermitted=function(){if("function"==typeof XMLHttpRequest||"object"==typeof XMLHttpRequest){var a=new XMLHttpRequest;return"1"==window.skbcsa2useCorsForInitialRequest&&"withCredentials"in a}return!1};var R=window.sessionStorage&&window.skbcsa2isCorsPermitted();l.skbcsa2GP=
function(a){try{return a===a.parent?null:a.parent}catch(d){}return null};l.skbcsa2TWID="AUTOSET";window.skbcsa2resetCSA=function(){window.skbcsa2doResetCSA&&window.skbcsa2doResetCSA()};window.skbcsa2doReInit=function(a){try{var d=window.sessionStorage?!0:!1;d&&window.skbcsa2sessionStorageEnabled&&(d=window.skbcsa2sessionStorageEnabled());if(d&&window.skbcsa2oTP){v();var c=y(),d="",d=g(c);d||(r(c,"reinit:"+window.skbcsa2windowID+(a?":1":":0")),v())}else window.skbcsa2executeReInitNow&&
window.skbcsa2executeReInitNow()}catch(b){}};window.skbcsa2executeReInitNow=function(a){window.skbcsa2qBU&&window.skbcsa2qBU();window.skbcsa2clearStoppedState&&window.skbcsa2clearStoppedState();l.skbcsa2lstActv=(new Date).valueOf();window.skbcsa2findCookieVal("skbcsa2P3P",1);window.skbcsa2resetCSA&&window.skbcsa2resetCSA();a&&(window.skbcsa2deleteSessionCookie&&window.skbcsa2deleteSessionCookie(),v());if(window.skbcsa2AppBridgeV2){window.skbcsa2awaitingAppResponse=
!0;try{var d=window.skbcsa2findCookieVal("skbcsa2persisted");window.skbcsa2AppBridgeV2.requestSessionInformation(location.href,d,window.skbcsa2windowId,!0)}catch(c){window.skbcsa2appSessionObject="",window.skbcsa2awaitingAppResponse=!1,window.skbcsa2getSD&&window.skbcsa2getSD(document.body,window,document,navigator)}}else window.skbcsa2getSD&&window.skbcsa2getSD(document.body,window,document,navigator)};window.skbcsa2tmoPoll=function(){var a=l.skbcsa2lstActv,d=
l.skbcsa2idl,c=(new Date).valueOf();-1!=a&&c-a>d&&window.skbcsa2doReInit&&window.skbcsa2doReInit();window.setTimeout(window.skbcsa2tmoPoll,1E4)};0===window.location.href.indexOf("file://")&&window.skbcsa2tmoPoll();window.skbcsa2jsInsertAlreadyLoaded=!1;l.skbcsa2getSD=function(g,d,n){function b(a,h,b){if(!h&&0!==h&&!1!==h)return b;h=c(h);b.length+a.length+h.length<=E&&(b=b+a+h);return b}function l(a,h,b,d,c,e,f){return a.length+b.length+d.length+c.length+h.length+e.length+f.length+
3+20<=E?!0:!1}function p(a,h){try{a||(a="");var b=a.split("_");if(5>b.length){var d=(new Date).valueOf();return h.sessionNumber+"_"+d+"_"+d+"_"+h.loadBalancerId+"_"+h.sessionKey}b[0]=h.sessionNumber;b[3]=h.loadBalancerId;b[4]=h.sessionKey;return b.join("_")}catch(c){return a}}function r(a,b){return b&&b.uvt?b.uvt:""}function y(a){var h="",h=window.skbcsa2isCorsPermitted()&&"1"==window.skbcsa2useJsonFormatForInitialCorsRequest?""+a+"/"+A+"/handler9/session.json?":""+a+"/"+A+"/handler9/session.js?";
a=e();window.skbcsa2appSessionObject?((a=window.skbcsa2appSessionObject)&&u&&(u.sessionInfo="x"+a.sessionNumber+"_"+a.loadBalancerId,u.loadBalancerID=a.loadBalancerId,u.sessionKey=a.sessionKey,u.sessionCookieVal=p(u.sessionCookieVal,a),persistedValFromAppComponents=r(u.persistedCookieVal,a).split("="),2==persistedValFromAppComponents.length&&(u.persistedCookieVal=persistedValFromAppComponents[1]),A=u.loadBalancerID,B=u.sessionInfo),h=b("se=",u.sessionInfo,h),h=b("&wf=",u.sessionCookieVal,h),
h=b("&wg=",u.persistedCookieVal,h),h=b("&tz=",u.sessionKey,h)):(h=u&&u.foundSessionCookie&&!u.foundLegacyCookie?b("se=",u.sessionInfo,h):b("se=",B,h),h=b("&wf=",u.sessionCookieVal,h),h=b("&wg=",u.persistedCookieVal,h),h=b("&di=",f(),h),h=b("&tz=",a,h));var g=window.skbcsa2consent,h=b("&us=",g,h),h=b("&sj=","skbcsa2",h),h=b("&aP=",d.skbcsa2windowID,h),h=b("&bd=",navigator.cookieEnabled,h),h=b("&si=",navigator.javaEnabled(),h),h=b("&aM=",Q(d),h);a=L();-2<a&&(h=b("&aO=",""+a,h));h=b("&vb=",
d.skbcsa2compatVersion,h);h=b("&wa=","8.19.19290",h);try{h=d.top.name?b("&aW=",d.top.name,h):b("&aW=",d.skbcsa2windowID,h)}catch(m){}a="not_available";try{a=d==d.top}catch(m){}h=b("&bu=",a,h);a=d.skbcsa2gC(T);if(window.skbcsa2appSessionObject){for(var q=a.celebrusCookies.split("; "),k=!1,t=!1,x=!1,w=0,V=q.length;w<V;w++){var v=q[w].split("=");2==v.length&&("skbcsa2session"==v[0]||"usy46gabsosd"==v[0]?(q[w]="skbcsa2session="+p(v[1],window.skbcsa2appSessionObject),k=!0):"skbcsa2persisted"==
v[0]?(q[w]=r(v[1],window.skbcsa2appSessionObject),t=!0):"skbcsa2P3P"==v[0]&&(q[w]="skbcsa2P3P="+g,x=!0))}k||(q[q.length]=p("",window.skbcsa2appSessionObject));t||(q[q.length]=r("",window.skbcsa2appSessionObject));x||(q[q.length]="skbcsa2P3P="+g);g=q.join("; ");a.celebrusCookies=g}k=a.siteCookies;g=c(a.celebrusCookies);if(h.length<E){q=[];q[0]=n.title;q[1]=k;q[2]=n.referrer;q[3]=location.href;(q[4]=d.skbcsa2PageID)||0===d.skbcsa2PageID||(q[4]="");for(t=k=!1;!l(h,c(q[0]),c(q[1]),
c(q[2]),c(q[3]),c(q[4]),g)&&!k;)k=0,c(q[1]).length>c(q[k]).length&&(k=1),c(q[2]).length>c(q[k]).length&&(k=2),c(q[3]).length>c(q[k]).length&&(k=3),c(q[4]).length>c(q[k]).length&&(k=4),q[k]=q[k].substring(0,Math.min(q[k].length/2,E-h.length-20)),t=!0,k=0===q[0].length&&0===q[1].length&&0===q[2].length&&0===q[3].length&&0===q[4].length;h=b("&cf=",q[0],h);h=b("&az=",a.celebrusCookies+"; "+q[1],h);h=b("&ar=",q[2],h);h=b("&au=",q[3],h);h=b("&sg=",q[4],h);t&&(h=b("&ic=","true",h))}return h}function v(){for(var a=
t(),b=0;a&&50>b;)if(0==a.indexOf("reinit:"))a=t(),b++;else return a;return null}function z(){var a,b;if(b=v()){J(b,":https")&&!H&&(H=!0,C=N);w();window.CelebrusLoggingUtils&&window.CelebrusLoggingUtils.logEventQueued(strEvt);a="";for(var d=0;b&&50>d;){a="";for(var c=x(b),e=0;b&&a.length+c.length<E&&50>e;)a=a+c+"&a=2",b=v(),J(b,":https")&&!H&&(H=!0,C=N),b&&(w(),c=x(b)),e++;b&&(c="https://TIVMITDDDT01.SKBDev.intra.skb",H||(c="http://TIVMITDDDT01.SKBDev.intra.skb"),resourcePath="1"==skbcsa2useJsonFormatForInitialCorsRequest?"/AEZ32ZHD01MJ/jsEvent.json?":
"/AEZ32ZHD01MJ/jsEvent.js?",c=c+resourcePath+"z="+a.substring(4),S(c));d++}window.skbcsa2LC(C+"&ipe="+a,"skbcsa2loadPageId")}else window.skbcsa2LC(C,"skbcsa2loadPageId")}function G(a,b,c,e,f,g,k,m){D=window.skbcsa2gPr();(a=n.cookie)||(a="");if(""==a&&window.sessionStorage){try{(a=window.sessionStorage.getItem("usy46gabsosd"))||(a="");c=b="";window.localStorage&&(b=window.localStorage.getItem("skbcsa2DBID"),c=window.localStorage.getItem("skbcsa2uvt"));var l=window.sessionStorage.getItem("skbcsa2key");
a=a?"usy46gabsosd="+a:"";b&&(a+="; skbcsa2DBID="+b);c&&(a+="; skbcsa2uvt="+c);l&&(a+="; skbcsa2key="+l)}catch(p){}T=a}a.length>O&&a.substring(0,O);if(u.foundLegacyCookie||u.foundSessionCookie)u.foundLegacyCookie&&!u.sessionCookieVal&&(b=a.indexOf("usy46gabsosd"),l=a.indexOf(";",b),-1==l&&(l=a.length),l=a.substring(b,l),c="skbcsa2__",e=l.indexOf(c),-1<e?(b=l.indexOf("::",e),0>b&&(b=l.indexOf(";",e)),0>b&&(b=l.length),B="x"+l.substring(e+c.length,b)):(c="skbcsa2_",e=l.indexOf(c),-1<e?(e+=c.length-
1,b=l.indexOf("::",e),0>b&&(b=l.indexOf(";",e)),0>b&&(b=l.length),B=l.substring(e,b)):(l=a.indexOf("usy46gabsosd="),b=a.indexOf(";",l),0>b&&(b=a.length),B=d.skbcsa2windowID+A,d.skbcsa2SC(a.substring(l,b)+"::skbcsa2"+d.skbcsa2windowID+A))));else{d.skbcsa2SC("usy46gabsosd=skbcsa2"+d.skbcsa2windowID+A);B=d.skbcsa2windowID+A;try{d.top.name||(d.top.name=d.skbcsa2windowID)}catch(p){}}I=y("http://TIVMITDDDT01.SKBDev.intra.skb");N=y("https://TIVMITDDDT01.SKBDev.intra.skb");C=H?N:I;!d.skbcsa2SF&&C.length<=E&&(window.CelebrusLoggingUtils&&window.CelebrusLoggingUtils.logConfigurationSent(C),
window.skbcsa2isCorsPermitted()?window.skbcsa2sendScriptRequests(C,D,z,window.skbcsa2processAppResponse):window.skbcsa2sendScriptRequests(C,D,"",window.skbcsa2processAppResponse));d.skbcsa2ae()}function L(a,b,c){if(P){a=P(d);try{if(!a||!a.frames)return-1;b=a.frames;for(c=0;c<b.length;c++)if(b[c]==d)return c}catch(e){}}return-1}u=a();F=k();var E=1940,O=1024,C="",D="",N="",I="";window.skbcsa2isCorsPermitted()&&(E=51200,O*=4);g=window;var M;M=window.skbcsa2appSessionObject&&window.skbcsa2appConsent?
window.skbcsa2appConsent:window.skbcsa2findCookieVal("skbcsa2P3P",1);g.skbcsa2consent=M;var H="https://TIVMITDDDT01.SKBDev.intra.skb"==window.skbcsa2gPr();window.skbcsa2processAppResponse=function(a,b,c,d){if(d!=window.skbcsa2windowId)for(var e=window.frames,f=0;f<e.length;f++)try{e[f].window.skbcsa2processAppResponse&&e[f].window.skbcsa2processAppResponse(a,b,c,d)}catch(g){}else window.skbcsa2isCorsPermitted()&&"1"==window.skbcsa2useJsonFormatForInitialCorsRequest?a&&window.skbcsa2executeJsonResponse(a,
c):window.skbcsa2dynamicCreateScript(b,"",a)};d.skbcsa2GPWID=function(a,b){if(!P)return"not_available";(b=P(a))||(b=a);try{return b.skbcsa2windowID}catch(c){return"not_available"}};var P=d.skbcsa2GP,Q=d.skbcsa2GPWID;d.skbcsa2Tm=(new Date).valueOf();R?G():K(G)};var M=window.skbcsa2initialExecutionCanProceed();!M&&window.skbcsa2findCookieVal("skbcsa2SF")?window.skbcsa2periodicAssessShutdownState():(M||window.SpeedTrapComponent)&&l.skbcsa2getSD(D.body,l,D)}};
window.skbcsa2sendScriptRequests=function(a,k,f,e){window.CelebrusLoggingUtils&&window.CelebrusLoggingUtils.isDryRun()?window.CelebrusLoggingUtils.executeResponseForDryRun():(window.sessionStorage&&f?f():window.skbcsa2LC(a,"skbcsa2loadPageId"),window.skbcsa2jsInsertAlreadyLoaded||(window.skbcsa2LC(""+k+"/JavascriptInsert.js","skbcsa2csaId"),window.skbcsa2jsInsertAlreadyLoaded=!0))};
window.skbcsa2cookieAllowsScriptToProceed=function(a){return-1<a.indexOf("skbcsa2SF=")?!1:!0};function skbcsa2Start(){function a(a){k&&(window.skbcsa2SL&&window.skbcsa2SL(),k=!1)}var k=!1;"prerender"==document.webkitVisibilityState||document.hidden?(k=!0,document.addEventListener&&(document.addEventListener("webkitvisibilitychange",a,!1),document.addEventListener("visibilitychange",a,!1))):window.skbcsa2SL&&window.skbcsa2SL()}
window.skbcsa2onInitialSessionInformationResponse=function(a,k,f){if(f!=window.skbcsa2windowId){for(var e=window.frames,c=0;c<e.length;c++)try{if(e[c].window.skbcsa2onInitialSessionInformationResponse&&e[c].window.skbcsa2onInitialSessionInformationResponse(a,k,f))return!0}catch(p){}return!1}try{e=window.skbcsa2awaitingAppResponse=!1;f="";if(a){try{f=JSON.parse(a)}catch(p){}f&&(window.skbcsa2appSessionObject&&(f.sessionNumber!=window.skbcsa2appSessionObject.sessionNumber||window.skbcsa2wid)&&
(e=!0),window.skbcsa2appSessionObject=f)}window.skbcsa2appConsent=k}catch(p){window.skbcsa2appSessionObject=""}e?window.skbcsa2getSD&&window.skbcsa2getSD(document.body,window,document,navigator):skbcsa2Start();return!0};
window.skbcsa2SC||(window.skbcsa2SC=function(a,k,f,e,c,p,g,r){var n=document,y=window,z="file:"==location.protocol;e=a+"; path=/;";var w=a.split("=");if(y.skbcsa2uSC){if("http:"==location.protocol)return;e+=" secure;"}if(!z){var v=e;k&&(e=e+"expires="+k);";"==e.charAt(e.length-1)&&(e=e.substring(0,e.length-1));y.skbcsa2GD&&(n.cookie=e+y.skbcsa2GD());if(!r&&-1<n.cookie.indexOf(a)&&!k)return;f=location.hostname;c=f.split(".");if(g){n.cookie=e+";domain="+g;return}if(2<=c.length){p=c.length-
2;g="."+c[p+1];do if(g="."+c[p]+g,n.cookie=e+"; domain="+g,p--,r)try{if(-1==document.cookie.indexOf(w[0]+"="))return}catch(x){}while((r&&-1<n.cookie.indexOf(w[0]+"=")||!r&&-1==n.cookie.indexOf(a))&&0<=p);if(!r&&-1==n.cookie.indexOf(a)&&v)for(p=c.length-2,g="."+c[p+1];-1==n.cookie.indexOf(a)&&0<=p;)g="."+c[p]+g,n.cookie=v+" domain="+g,p--}0!==location.href.indexOf("file://")&&(r&&-1<n.cookie.indexOf(a)||!r&&-1==n.cookie.indexOf(a))&&(r?(f=new Date,f.setFullYear(1970),n.cookie=v+" domain="+location.hostname+
"; expires="+f.toGMTString()):n.cookie=v+" domain="+location.hostname)}if(z||!r&&-1==n.cookie.indexOf(a)){a=a.split("=");try{var t=window.sessionStorage;k&&(t=window.localStorage);t&&(a[1]&&-1<a[1].indexOf(";")&&(a[1]=a[1].substring(0,a[1].indexOf(";"))),r?t.removeItem(a[0]):t.setItem(a[0],a[1]));return}catch(x){}y.skbcsa2SF=1}});
window.skbcsa2findCookieVal=function(a,k){if(document.cookie)for(var f=document.cookie.split("; "),e=0;e<f.length;e++){var c=f[e].split("=");try{if(c[0]==a)return c[1]}catch(g){}}f="";try{var p=window.sessionStorage;if(k||"skbcsa2uvt"==a||"skbcsa2DBID"==a||"skbcsa2persisted"==a)p=window.localStorage;p&&(f=p.getItem(a))}catch(g){}return f};
window.skbcsa2deleteLegacyCookies=function(){var a=!0,k=skbcsa2findCookieVal("usy46gabsosd",!1);k&&1<k.split("::").length&&(a=!1);if(document.cookie)window.skbcsa2SC&&(a&&window.skbcsa2doDeleteCookie("usy46gabsosd"),window.skbcsa2doDeleteCookie("skbcsa2uvt"),window.skbcsa2doDeleteCookie("skbcsa2key"),window.skbcsa2doDeleteCookie("skbcsa2DBID"));else try{window.sessionStorage&&(a&&window.sessionStorage.removeItem("usy46gabsosd"),window.sessionStorage.removeItem("skbcsa2key")),
window.localStorage&&(window.localStorage.removeItem("skbcsa2uvt"),window.localStorage.removeItem("skbcsa2DBID"))}catch(f){}};window.skbcsa2doDeleteCookie=function(a,k){var f=new Date;f.setFullYear(1970);window.skbcsa2SC&&window.skbcsa2SC(a+"=0",f.toGMTString(),"","","","",k,!0)};function skbcsa2sessionset(a){skbcsa2SC("skbcsa2session="+a)}
function skbcsa2persisted(a,k,f,e,c,p,g,r,n,y){var z=new Date,w,v=0,t;a:{var x=document.cookie;""==x&&window.localStorage&&(x=(x=window.localStorage.getItem("skbcsa2persisted"))?"skbcsa2persisted="+x:"");x=x.split("; ");t=0;for(var J=x.length;t<J;t++){var K=x[t].split("=");if(1<K.length&&c==K[0]){t=unescape(K[1]);break a}}t=null}g&&(v=g);x=!0;t&&(t=t.split("_"),7<=t.length&&(e==t[4]&&(x=!1),t[2]&&(w=t[2],r=t[3],v=t[6])));x&&(g||v++);w||(w=f);z.setTime(z.getTime()+p);y?skbcsa2SC(c+"="+
a+"_"+k+"_"+w+"_"+r+"_"+e+"_"+n+"_"+v,z.toGMTString()):skbcsa2SC(c+"="+a+"_"+k+"_____",z.toGMTString())}
function skbcsa2legacyset(a,k,f,e){var c=window,p=document.cookie;c.skbcsa2GD&&c.skbcsa2GD();var g=p.indexOf("usy46gabsosd"),r="";if(-1==g)window.skbcsa2SC&&window.skbcsa2SC("usy46gabsosd=skbcsa2__"+a+"_"+k+"_"+f+e);else{var r=p.indexOf(";",g),n=c="";0>r&&(r=p.length);p=p.substring(g+12+1,r);g=p.indexOf("skbcsa2");-1<g?(c=p.substring(0,g),""!=c&&(c="::"+c),g=p.indexOf("::",g),-1<g&&(n=""==c?p.substring(g):p.substring(g+2))):c="::"+p;r="usy46gabsosd=skbcsa2__"+a+"_"+k+"_"+f+
e;""!=c&&(r+=c);""!=n&&(r+=n);window.skbcsa2SC&&window.skbcsa2SC(r)}}function skbcsa2keyset(a,k){skbcsa2SC("skbcsa2key="+a)}function skbcsa2DBIDset(a,k){var f=new Date;f.setTime(f.getTime()+k);skbcsa2SC("skbcsa2DBID="+a,f.toGMTString())}
function skbcsa2uvt(a,k,f,e,c){var p=new Date,g,r=0,n;a:{n=document.cookie;""==n&&window.localStorage&&(n=(n=window.localStorage.getItem("skbcsa2uvt"))?"skbcsa2uvt="+n:"");n=n.split("; ");for(var y=0,z=n.length;y<z;y++){var w=n[y].split("=");if(1<w.length&&"skbcsa2uvt"==w[0]){n=unescape(w[1]);break a}}n=null}if(n&&(n=n.split("_"),5<=n.length)){if(k==n[2])return;g=n[0];e=n[1];r=n[4]}r++;g||(g=a);p.setTime(p.getTime()+f);skbcsa2SC("skbcsa2uvt="+g+"_"+e+"_"+k+"_"+c+"_"+r,p.toGMTString())}
function skbcsa2setShutdown(){window.skbcsa2deleteSessionCookie&&window.skbcsa2deleteSessionCookie();var a=(new Date).valueOf();if(window.skbcsa2GD){var k=window.skbcsa2GD();document.cookie="skbcsa2SF="+a+";path=/"+k}else window.skbcsa2SC&&window.skbcsa2SC("skbcsa2SF="+a)}
function skbcsa2Go(){try{var a=window.crypto||window.msCrypto;window.skbcsa2generateUUID=function(){return"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx".replace(/[x]/g,function(a){return(16*Math.random()|0).toString(16)})};"undefined"!=typeof a&&"undefined"!=typeof a.getRandomValues&&(window.skbcsa2generateUUID=function(){var f=new Uint16Array(8);a.getRandomValues(f);var e=function(a){for(a=a.toString(16);4>a.length;)a="0"+a;return a};return""+e(f[0])+e(f[1])+e(f[2])+e(f[3])+e(f[4])+e(f[5])+e(f[6])+
e(f[7])});window.skbcsa2windowId="_"+(new Date).getTime()+"0."+window.skbcsa2generateUUID()+"_";if(window.skbcsa2AppBridgeV2){window.skbcsa2awaitingAppResponse=!0;try{var k=window.skbcsa2findCookieVal("skbcsa2persisted",!0);window.skbcsa2AppBridgeV2.requestSessionInformation(location.href,k,window.skbcsa2windowId,!0)}catch(f){window.skbcsa2appSessionObject="",window.skbcsa2awaitingAppResponse=!1,skbcsa2Start()}}else window.skbcsa2awaitingAppResponse=!1,skbcsa2Start()}catch(f){}}
skbcsa2Go();
window.skbcsa2RTEHandler={maxWaitDurationMillis:1E4,maxActionProcessDurationMillisToAllowRequeue:50,targetMissingPollingDurationMillis:250,domContentReadyPollingDurationMillis:100,injectionCount:0,staleCount:0,rejectedCount:0,errorCount:0,nameVal:"RTEHandler",currentActionID:"",currentRuleID:"",currentContentID:"",currentCustomID:"",queue:[],isDomContentReady:function(){var a=document.getElementsByTagName("body");return a&&0!==a.length?"complete"==document.readyState||"loaded"==document.readyState||
"interactive"==document.readyState?!0:!1:!1},reset:function(){this.queue=[];this.errorCount=this.rejectedCount=this.staleCount=this.injectionCount=0},getTimestampMillis:function(){return(new Date).getTime()},handleResponse:function(a,c){if(!a||!a.length||!c&&-1<document.cookie.indexOf("skbcsa2SF=y"))return 0;var b=this.getTimestampMillis(),d,e,f;d=0;for(e=a.length;d<e;d++){f=a[d];try{f.queueTimestampMillis=b;if(f.content&&(f.content=this.doUnescape(f.content),f.parsedContent=this.parseContent(f.content),
!f.parsedContent)){this.rejectedCount++;continue}f.externalContentId&&(f.externalContentId=this.doUnescape(f.externalContentId));f.replacementurl&&(f.replacementurl=this.doUnescape(f.replacementurl));f.idValue&&(f.idValue=this.doUnescape(f.idValue));this.validVariables(f.csaNumber,f.contentKey)?f.csaCallbackTime?this.doCallback(f):this.queueAction(f):this.distributeActionToChildCsas(f)||this.queueAction(f)}catch(g){this.rejectedCount++,this.handleError(g)}}return this.processQueue()},doCallback:function(a){window.skbcsa2dCB?
window.skbcsa2dCB(parseInt(a.csaCallbackTime),this.getTimestampMillis()):(window.skbcsa2dCBValTS=this.getTimestampMillis(),window.skbcsa2dCBVal=parseInt(a.csaCallbackTime))},queueAction:function(a){this.queue.unshift(a)},isOlderThan:function(a,c){var b=this.getTimestampMillis();return Math.abs(b-c)>a},isActionStale:function(a){return this.isOlderThan(this.maxWaitDurationMillis,a.queueTimestampMillis)},processQueue:function(){if(0===this.queue.length)return 0;if(!this.isDomContentReady()){var a=
this;window.setTimeout(function(){a.processQueue.call(a)},this.domContentReadyPollingDurationMillis);return 0}var c=0,b;for(b=this.queue.length-1;0<=b;b--){var d=this.queue[b];try{if(this.isActionStale(d))this.staleCount++,this.queue.splice(b,1);else{var e=this.getTimestampMillis();this.processAction(d)?(this.injectionCount++,this.queue.splice(b,1),this.actionsExecutedCount++,c++):this.isOlderThan(this.maxActionProcessDurationMillisToAllowRequeue,e)&&(this.rejectedCount++,this.queue.splice(b,1))}}catch(f){this.queue.splice(b,
1),this.handleError(f)}}0<this.queue.length&&(a=this,window.setTimeout(function(){a.processQueue.call(a)},this.targetMissingPollingDurationMillis));return c},processAction:function(a){return this.validVariables(a.csaNumber,a.contentKey)?(this.currentActionID=a.actionID,this.currentRuleID=a.ruleID,this.currentContentID=a.contentID,this.currentCustomID=a.customID,a=this.updateContent(a),this.currentCustomID=this.currentContentID=this.currentRuleID=this.currentActionID="",a):this.distributeActionToChildCsas(a)},
validVariables:function(a,c){return window.skbcsa2wid!=a||c&&c!=window.skbcsa2contentKey?!1:!0},isObjectInArray:function(a,c){if(!c||!a)return!1;for(var b=0,d=c.length;b<d;b++)if(c[b]===a)return!0;return!1},recurseChildCsas:function(a,c,b){var d=-1;try{d=a.skbcsa2wid}catch(f){return!1}if(d==c.csaNumber){if(a.skbcsa2RTEHandler)return c.csaCallbackTime&&a.skbcsa2RTEHandler.doCallback(c),a.skbcsa2RTEHandler.queueAction(c),this.isObjectInArray(a,b)||b.push(a),!0}else try{if(a.frames&&
0<a.frames.length)for(var d=0,e=a.frames.length;d<e;d++)if(this.recurseChildCsas(a.frames[d],c,b))return!0}catch(f){}return!1},distributeActionToChildCsas:function(a){if(window.skbcsa2gHW){var c=[];a=this.recurseChildCsas(window.skbcsa2gHW(),a,c);if(0<c.length)for(var b=0,d=c.length;b<d;b++)c[b].skbcsa2RTEHandler.processQueue();return a}return!1},insertNodeAfter:function(a,c){var b=c.parentNode;b.lastchild==c?b.appendChild(a):b.insertBefore(a,c.nextSibling)},getParentElement:function(a){return a.parentElement?
a.parentElement:a.parentNode?a.parentNode:""},replaceImage:function(a,c,b){if(b){for(var d=!1,e=a;a&&!d;){if(a.href&&("a"==(""+a.tagName).toLowerCase()||"area"==(""+a.tagName).toLowerCase())){a.href=b;d=!0;break}var f=this.getParentElement(a);if(a===f)break;a=f}if(d)e.src=c;else if(a=document.createElement("SPAN"),d=document.createElement("A"),d.href=b,a.appendChild(d),b=this.getParentElement(e))b.replaceChild(a,e),d.appendChild(e),e.src=c,e.setAttribute("style","border-style: none")}else a.src=c},
doUnescape:function(a){window.decodeURIComponent||(a=a.replace(/%C2%A3/g,"%A3"));a=a.replace(/\\+/g,"%20");return a=window.decodeURIComponent?window.decodeURIComponent(a):unescape(a)},pushContentAddedData:function(a){this.currentActionID&&(window.skbcsa2variableStateChange?window.skbcsa2reportContentAction(this.currentActionID,this.currentRuleID,this.currentContentID,this.currentCustomID):(window.skbcsa2ContentIdArray||(window.skbcsa2ContentIdArray=[]),window.skbcsa2ContentIdArray[window.skbcsa2ContentIdArray.length]=
{actionId:this.currentActionID,ruleId:this.currentRuleID,contentId:this.currentContentID,customId:this.currentCustomID}))},getFormName:function(a){if(!a)return"";var c=a.getAttribute("name");return c?c:a.name&&!a.name.type?a.name:""},getFormID:function(a){if(!a)return"";var c=a.getAttribute("id");return c?c:a.id&&!a.id.type?a.id:""},getElementClass:function(a){var c=a.getAttribute("class");c||(c=a.getAttribute("className"));return c},findMatchesByParentFormName:function(a,c,b){var d=new RegExp(c);
a||(a=document.getElementsByTagName("*"));for(var e=[],f=0,g=a.length;f<g;f++)if(a[f].form){var h=this.getFormName(a[f].form);b?d.test(h)&&(e[e.length]=a[f]):c==h&&(e[e.length]=a[f])}return e},findMatchesByParentFormID:function(a,c,b){var d=new RegExp(c);a||(a=document.getElementsByTagName("*"));for(var e=[],f=0,g=a.length;f<g;f++)if(a[f].form){var h=this.getFormID(a[f].form);b?d.test(h)&&(e[e.length]=a[f]):c==h&&(e[e.length]=a[f])}return e},findMatchesByName:function(a,c,b){a||(a=document.getElementsByTagName("*"));
var d=[];if(b)for(c=new RegExp(c),b=0;b<a.length;b++)c.test(a[b].name)&&(d[d.length]=a[b]);else for(c=c?c.toLowerCase():c,b=0;b<a.length;b++){var e=(""+a[b].name).toLowerCase();c==e&&(d[d.length]=a[b])}return d},findMatchesById:function(a,c,b){a||(a=document.getElementsByTagName("*"));var d=[];if(b)for(c=new RegExp(c),b=0;b<a.length;b++)c.test(a[b].id)&&(d[d.length]=a[b]);else for(b=0;b<a.length;b++)c==a[b].id&&(d[d.length]=a[b]);return d},findMatchesByClass:function(a,c,b){a||(a=document.getElementsByTagName("*"));
var d=[];if(b)for(c=new RegExp(c),b=0;b<a.length;b++)c.test(this.getElementClass(a[b]))&&(d[d.length]=a[b]);else for(b=0;b<a.length;b++)c==this.getElementClass(a[b])&&(d[d.length]=a[b]);return d},findMatchesByHref:function(a,c,b){a||(a=document.getElementsByTagName("A"));var d=[];if(b)for(c=new RegExp(c),b=0;b<a.length;b++)c.test(a[b].href)&&(d[d.length]=a[b]);else for(c=c.toLowerCase(),b=0;b<a.length;b++){var e=(""+a[b].href).toLowerCase();c==e&&(d[d.length]=a[b])}return d},findMatchesBySrc:function(a,
c,b){a||(a=document.getElementsByTagName("IMG"));var d=[];if(b)for(c=new RegExp(c),b=0;b<a.length;b++)c.test(a[b].src)&&(d[d.length]=a[b]);else for(c=c.toLowerCase(),b=0;b<a.length;b++){var e=(""+a[b].src).toLowerCase();c==e&&(d[d.length]=a[b])}return d},findMatchesByTagName:function(a,c,b){c=c.toUpperCase();a||(a=document.getElementsByTagName("*"));var d=[];if(b)for(c=new RegExp(c),b=0;b<a.length;b++)c.test((""+a[b].tagName).toUpperCase())&&(d[d.length]=a[b]);else for(b=0;b<a.length;b++){var e=(""+
a[b].tagName).toUpperCase();c==e&&(d[d.length]=a[b])}return d},findMatchesByType:function(a,c,b){c=c.toLowerCase();a||(a=document.getElementsByTagName("*"));var d=[];if(b)for(c=new RegExp(c),b=0;b<a.length;b++)c.test((""+a[b].type).toLowerCase())&&(d[d.length]=a[b]);else for(b=0;b<a.length;b++){var e=(""+a[b].type).toLowerCase();c==e&&(d[d.length]=a[b])}return d},updateContent:function(a){"undefined"!=typeof SpeedTrapComponent&&SpeedTrapComponent.logMessage("Inserting "+a.parsedContent);if(3==a.csaAction)return this.insertContentAtTopOfPage(a.parsedContent),
!0;if(4==a.csaAction)return this.insertContentAtEndOfPage(a.parsedContent),!0;if(!a.attributesArray)return!1;for(var c=!1,b=null,d="",e="",f="",g="",h="",p="",k=0,q=a.attributesArray.length;k<q;k++){var l=a.attributesArray[k].attributeType,m=a.attributesArray[k].attributeValue,n=a.attributesArray[k].attributeIsRegEx;"NAME"==l?b=this.findMatchesByName(b,m,n):"ID"==l?b=this.findMatchesById(b,m,n):"CLASS"==l?b=this.findMatchesByClass(b,m,n):"IMAGE"==l?(d={val:m,isRegex:n},c=!0):"ANCHOR"==l?e={val:m,
isRegex:n}:"TAGNAME"==l?f={val:m,isRegex:n}:"FORM_NAME"==l?g={val:m,isRegex:n}:"FORM_ID"==l?h={val:m,isRegex:n}:"TYPE"==l&&(p={val:m,isRegex:n})}g&&(b=this.findMatchesByParentFormName(b,g.val,g.isRegex));h&&(b=this.findMatchesByParentFormID(b,h.val,h.isRegex));e&&(b=this.findMatchesByHref(b,e.val,e.isRegex));d&&(b=this.findMatchesBySrc(b,d.val,d.isRegex));f&&(b=this.findMatchesByTagName(b,f.val,f.isRegex));p&&(b=this.findMatchesByType(b,p.val,p.isRegex));if(null===b)return!1;e=!1;for(k=0;k<b.length;k++)d=
b[k],f=(""+b[k].tagName).toUpperCase(),"HEAD"!=f&&"META"!=f&&(c&&"IMAGE"==a.replacementContentType?(0==a.csaAction?(this.replaceImage(d,a.parsedContent.childNodes[0].nodeValue,a.replacementurl),this.tagContent(d)):1==a.csaAction?(e=this.toInnerHtmlNode(a.parsedContent.childNodes[0]),(f=d.parentNode)&&f.insertBefore(e,d)):2==a.csaAction&&(e=this.toInnerHtmlNode(a.parsedContent.childNodes[0]),this.insertNodeAfter(e,d)),e=!0):(e=!0,this.modifyTarget(d,a)),this.pushContentAddedData());return e},insertContentAtTopOfPage:function(a){var c=
document.createElement("SPAN");this.tagContent(c);var b=document.getElementsByTagName("body")[0];b&&(b.insertBefore(c,b.firstChild),this.appendToDoc(c,a),this.pushContentAddedData())},insertContentAtEndOfPage:function(a){var c=document.createElement("SPAN");this.tagContent(c);var b=document.getElementsByTagName("body")[0];b&&(b.appendChild(c),this.appendToDoc(c,a),this.pushContentAddedData())},modifyTarget:function(a,c){if(a){var b=document.createElement("SPAN");this.tagContent(b);var d=a.parentNode;
0==c.csaAction?d&&d.replaceChild(b,a):1==c.csaAction?d&&d.insertBefore(b,a):2==c.csaAction&&this.insertNodeAfter(b,a);this.appendToDoc(b,c.parsedContent)}},parseContent:function(a){if(window.DOMParser)a=(new DOMParser).parseFromString(a,"text/xml");else{var c=new ActiveXObject("Microsoft.XMLDOM");c.async="false";c.loadXML(a);a=c}a=a.getElementsByTagName("strtecontent");return 1==a.length?a[0]:null},getHeadReference:function(){var a=document.getElementsByTagName("HEAD");return 0<a.length?a[0]:null},
appendToDoc:function(a,c){var b=null,d=c.nodeName.toUpperCase();if("STRTECONTENT"==d)b=a;else if("HEAD"==d){var e=this.getHeadReference();if(e){for(d=0;d<c.childNodes.length;d++)this.appendToDoc(e,c.childNodes[d]);return}}else if(b=this.createNewNode(c,a),null===b)return;e=0===d.indexOf("FB");if("SCRIPT"!=d&&"NOSCRIPT"!=d&&"STYLE"!=d&&"OBJECT"!=d&&"TABLE"!=d&&"H1"!=d&&"H2"!=d&&"H3"!=d&&"H4"!=d&&"H5"!=d&&"H6"!=d&&!e)for(d=0;d<c.childNodes.length;d++)this.appendToDoc(b,c.childNodes[d])},createNewNode:function(a,
c){var b;if(3==a.nodeType)b=document.createTextNode(a.nodeValue),c.appendChild(b);else{if(1==a.nodeType){b=a.nodeName.toUpperCase();var d=0===b.indexOf("FB");"OBJECT"==b||"TABLE"==b||"H1"==b||"H2"==b||"H3"==b||"H4"==b||"H5"==b||"H6"==b||d?(b=this.createObjectNode(a),c.appendChild(b)):"SCRIPT"==b?b=this.createScriptNode(a,c):"NOSCRIPT"==b?(b=this.createNoScriptNode(a),c.appendChild(b)):"STYLE"==b?b=this.createStyleNode(a,c):(b=document.createElement(a.nodeName.toUpperCase()),this.copyAttributes(a,
b),c.appendChild(b));return b}return null}},createObjectNode:function(a){return this.toInnerHtmlNode(a)},tagInjectedContent:function(a,c,b,d,e){a&&(c&&(a.skbcsa2contentActionIdentifier=c),b&&(a.skbcsa2ruleIdentifier=b),d&&(a.skbcsa2contentIdentifier=d),e&&(a.skbcsa2customIdentifier=e))},tagContent:function(a){this.tagInjectedContent(a,this.currentActionID,this.currentRuleID,this.currentContentID,this.currentCustomID)},toXML:function(a){return"undefined"!=typeof XMLSerializer?(new XMLSerializer).serializeToString(a):
a.xml?a.xml:""},toInnerHtmlNode:function(a){var c=document.createElement("SPAN");c.innerHTML=this.toXML(a);this.tagContent(c);return c},createScriptNode:function(a,c){var b=document.createElement("SCRIPT");c.appendChild(b);var d=a.attributes.getNamedItem("type");d&&(b.type=d.value);if(d=a.attributes.getNamedItem("src"))b.src=d.value;0<a.childNodes.length&&(b.text=a.childNodes[0].nodeValue);return b},createNoScriptNode:function(a){for(var c=document.createElement("NOSCRIPT"),b=document.createElement("SPAN"),
d=0;d<a.childNodes.length;d++)this.appendToDoc(b,a.childNodes[d]);c.text=b.innerHTML;return c},createStyleNode:function(a,c){var b=document.createElement("STYLE");c.appendChild(b);var d=a.attributes.getNamedItem("type");d&&(b.type=d.value);if(d=a.attributes.getNamedItem("src"))b.src=d.value;if(d=a.attributes.getNamedItem("media"))b.media=d.value;0<a.childNodes.length&&(b.styleSheet?b.styleSheet.cssText=a.childNodes[0].nodeValue:b.innerHTML=this.toXML(a.childNodes[0]));return b},copyAttributes:function(a,
c){for(var b=null,d=null,e=0,f=a.attributes.length;e<f;e++){var g=""+a.attributes[e].name,h=a.attributes[e].value;if("style"==g.toLowerCase())c.style.cssText=h;else if("class"==g.toLowerCase())window.attachEvent?c.className=h:c.setAttribute(g,h);else if("type"==g){b=h;continue}"value"==g?d=h:c.setAttribute(g,h)}b&&c.setAttribute("type",b);d&&(c.setAttribute("value",d),c.value=d)},handleError:function(a){this.errorCount++;if(window.SpeedTrapComponent){var c;c="There was an error.\n"+("Error description: "+
a.message+"\n");c+="Line no: "+a.lineNumber+"\n";a.stack&&(c+="Stack: "+a.stack);window.SpeedTrapComponent.logMessage("Error "+c)}}};
;